// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AssignmentUpdate
 */
export type AssignmentUpdate = {
    /**
     * Assigned Membership Id
     */
    assigned_membership_id: string | null;
};

/**
 * Body_auth-password_login
 */
export type Body_auth_password_login = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CommentCreate
 */
export type CommentCreate = {
    /**
     * Entry Version Id
     */
    entry_version_id: string;
    /**
     * Start Offset
     */
    start_offset: number;
    /**
     * End Offset
     */
    end_offset: number;
    /**
     * Exact Quote
     */
    exact_quote: string;
    /**
     * Prefix
     */
    prefix?: string;
    /**
     * Suffix
     */
    suffix?: string;
    /**
     * Body
     */
    body: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Mentioned User Ids
     */
    mentioned_user_ids?: Array<string>;
    /**
     * Assigned Membership Id
     */
    assigned_membership_id?: string | null;
};

/**
 * CommentPublic
 */
export type CommentPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Entry Id
     */
    entry_id: string;
    /**
     * Entry Version Id
     */
    entry_version_id: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Body
     */
    body: string;
    /**
     * Anchor State
     */
    anchor_state: string;
    /**
     * Review Required
     */
    review_required: boolean;
    /**
     * Assigned Membership Id
     */
    assigned_membership_id: string | null;
    /**
     * Mentioned User Ids
     */
    mentioned_user_ids?: Array<string>;
    /**
     * Resolved At
     */
    resolved_at: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * DemoLoginRequest
 */
export type DemoLoginRequest = {
    /**
     * Persona
     */
    persona: 'patient' | 'staff' | 'clinician' | 'admin' | 'worker' | 'other_staff';
};

/**
 * DiffPublic
 */
export type DiffPublic = {
    /**
     * From Version Id
     */
    from_version_id: string;
    /**
     * To Version Id
     */
    to_version_id: string;
    /**
     * Unified Diff
     */
    unified_diff: string;
};

/**
 * EntryCreate
 */
export type EntryCreate = {
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Section
     */
    section: 'patient' | 'staff' | 'clinician' | 'system';
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * Patient Facing
     */
    patient_facing?: boolean;
    /**
     * Origin
     */
    origin?: 'human' | 'ai' | 'system';
    /**
     * Supersedes Entry Id
     */
    supersedes_entry_id?: string | null;
    /**
     * Conflicts With Entry Id
     */
    conflicts_with_entry_id?: string | null;
};

/**
 * EntryPatch
 */
export type EntryPatch = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Patient Facing
     */
    patient_facing?: boolean | null;
};

/**
 * EntryPublic
 */
export type EntryPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Clinic Id
     */
    clinic_id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Section
     */
    section: string;
    /**
     * Origin
     */
    origin: string;
    /**
     * Patient Facing
     */
    patient_facing: boolean;
    /**
     * Version Id
     */
    version_id: string;
    /**
     * Version No
     */
    version_no: number;
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * EntryVersionPublic
 */
export type EntryVersionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Entry Id
     */
    entry_id: string;
    /**
     * Version No
     */
    version_no: number;
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * Content Sha256
     */
    content_sha256: string;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Reverted From Version Id
     */
    reverted_from_version_id: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * EntryVersionsPublic
 */
export type EntryVersionsPublic = {
    /**
     * Data
     */
    data: Array<EntryVersionPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * GlanceCard
 */
export type GlanceCard = {
    /**
     * Highlight Id
     */
    highlight_id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Critical
     */
    critical: boolean;
    /**
     * Pinned
     */
    pinned: boolean;
    /**
     * Risk Reason
     */
    risk_reason: string;
    /**
     * Provenance Pointer Id
     */
    provenance_pointer_id: string;
};

/**
 * GlancePublic
 */
export type GlancePublic = {
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Source
     */
    source?: 'precomputed';
    /**
     * Generated At
     */
    generated_at: string;
    /**
     * Cards
     */
    cards: Array<GlanceCard>;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HighlightCreate
 */
export type HighlightCreate = {
    /**
     * Entry Version Id
     */
    entry_version_id: string;
    /**
     * Start Offset
     */
    start_offset: number;
    /**
     * End Offset
     */
    end_offset: number;
    /**
     * Exact Quote
     */
    exact_quote: string;
    /**
     * Prefix
     */
    prefix?: string;
    /**
     * Suffix
     */
    suffix?: string;
    /**
     * Label
     */
    label: string;
    /**
     * Critical
     */
    critical?: boolean;
    /**
     * Patient Facing
     */
    patient_facing?: boolean;
};

/**
 * HighlightPublic
 */
export type HighlightPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Entry Id
     */
    entry_id: string;
    /**
     * Source Entry Version Id
     */
    source_entry_version_id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Status
     */
    status: string;
    /**
     * Pinned
     */
    pinned: boolean;
    /**
     * Critical
     */
    critical: boolean;
    /**
     * Patient Facing
     */
    patient_facing: boolean;
    /**
     * Anchor State
     */
    anchor_state: string;
    /**
     * Review Required
     */
    review_required: boolean;
    /**
     * Provenance Pointer Id
     */
    provenance_pointer_id: string;
};

/**
 * MePublic
 */
export type MePublic = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * Clinic Id
     */
    clinic_id: string;
    /**
     * Membership Id
     */
    membership_id: string;
    /**
     * Role
     */
    role: 'patient' | 'staff' | 'clinician' | 'admin' | 'worker';
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * PatientPublic
 */
export type PatientPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Display Name
     */
    display_name: string;
};

/**
 * PatientTimeline
 */
export type PatientTimeline = {
    /**
     * Data
     */
    data: Array<PatientTimelineEntry>;
    /**
     * Count
     */
    count: number;
};

/**
 * PatientTimelineEntry
 */
export type PatientTimelineEntry = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Section
     */
    section: string;
    /**
     * Patient Facing
     */
    patient_facing: boolean;
    /**
     * Version Id
     */
    version_id: string;
    /**
     * Version No
     */
    version_no: number;
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PatientsPublic
 */
export type PatientsPublic = {
    /**
     * Data
     */
    data: Array<PatientPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ProvenanceResolved
 */
export type ProvenanceResolved = {
    /**
     * Id
     */
    id: string;
    /**
     * Entry Version Id
     */
    entry_version_id: string;
    /**
     * State
     */
    state: string;
    /**
     * Review Required
     */
    review_required: boolean;
    /**
     * Start Offset
     */
    start_offset: number;
    /**
     * End Offset
     */
    end_offset: number;
    /**
     * Exact Quote
     */
    exact_quote: string;
    /**
     * Prefix
     */
    prefix: string;
    /**
     * Suffix
     */
    suffix: string;
    /**
     * Quote Sha256
     */
    quote_sha256: string;
    /**
     * Audio Asset Id
     */
    audio_asset_id: string | null;
    /**
     * Audio Start Ms
     */
    audio_start_ms: number | null;
    /**
     * Audio End Ms
     */
    audio_end_ms: number | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type authDemoLoginData = {
    body: DemoLoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/demo-login';
};

export type authDemoLoginErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authDemoLoginError = authDemoLoginErrors[keyof authDemoLoginErrors];

export type authDemoLoginResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type authDemoLoginResponse = authDemoLoginResponses[keyof authDemoLoginResponses];

export type authPasswordLoginData = {
    body: Body_auth_password_login;
    headers: {
        /**
         * X-Clinic-Id
         */
        'X-Clinic-ID': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type authPasswordLoginErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authPasswordLoginError = authPasswordLoginErrors[keyof authPasswordLoginErrors];

export type authPasswordLoginResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type authPasswordLoginResponse = authPasswordLoginResponses[keyof authPasswordLoginResponses];

export type authMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type authMeResponses = {
    /**
     * Successful Response
     */
    200: MePublic;
};

export type authMeResponse = authMeResponses[keyof authMeResponses];

export type authLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type authLogoutResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type authLogoutResponse = authLogoutResponses[keyof authLogoutResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type patientsPatientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/patients';
};

export type patientsPatientsResponses = {
    /**
     * Successful Response
     */
    200: PatientsPublic;
};

export type patientsPatientsResponse = patientsPatientsResponses[keyof patientsPatientsResponses];

export type patientsPatientTimelineData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/patients/{patient_id}/timeline';
};

export type patientsPatientTimelineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsPatientTimelineError = patientsPatientTimelineErrors[keyof patientsPatientTimelineErrors];

export type patientsPatientTimelineResponses = {
    /**
     * Successful Response
     */
    200: PatientTimeline;
};

export type patientsPatientTimelineResponse = patientsPatientTimelineResponses[keyof patientsPatientTimelineResponses];

export type patientsPatientGlanceData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/patients/{patient_id}/glance';
};

export type patientsPatientGlanceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsPatientGlanceError = patientsPatientGlanceErrors[keyof patientsPatientGlanceErrors];

export type patientsPatientGlanceResponses = {
    /**
     * Successful Response
     */
    200: GlancePublic;
};

export type patientsPatientGlanceResponse = patientsPatientGlanceResponses[keyof patientsPatientGlanceResponses];

export type entriesCreateData = {
    body: EntryCreate;
    path?: never;
    query?: never;
    url: '/api/v1/entries';
};

export type entriesCreateErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type entriesCreateError = entriesCreateErrors[keyof entriesCreateErrors];

export type entriesCreateResponses = {
    /**
     * Response Entries-Create
     *
     * Successful Response
     */
    201: EntryPublic | PatientTimelineEntry;
};

export type entriesCreateResponse = entriesCreateResponses[keyof entriesCreateResponses];

export type entriesReadData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/entries/{entry_id}';
};

export type entriesReadErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type entriesReadError = entriesReadErrors[keyof entriesReadErrors];

export type entriesReadResponses = {
    /**
     * Response Entries-Read
     *
     * Successful Response
     */
    200: EntryPublic | PatientTimelineEntry;
};

export type entriesReadResponse = entriesReadResponses[keyof entriesReadResponses];

export type entriesPatchData = {
    body: EntryPatch;
    headers?: {
        /**
         * If-Match
         */
        'If-Match'?: string | null;
    };
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/entries/{entry_id}';
};

export type entriesPatchErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type entriesPatchError = entriesPatchErrors[keyof entriesPatchErrors];

export type entriesPatchResponses = {
    /**
     * Response Entries-Patch
     *
     * Successful Response
     */
    200: EntryPublic | PatientTimelineEntry;
};

export type entriesPatchResponse = entriesPatchResponses[keyof entriesPatchResponses];

export type entriesVersionsData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/entries/{entry_id}/versions';
};

export type entriesVersionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type entriesVersionsError = entriesVersionsErrors[keyof entriesVersionsErrors];

export type entriesVersionsResponses = {
    /**
     * Successful Response
     */
    200: EntryVersionsPublic;
};

export type entriesVersionsResponse = entriesVersionsResponses[keyof entriesVersionsResponses];

export type entriesDiffData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
        /**
         * Version Id
         */
        version_id: string;
    };
    query: {
        /**
         * Against
         */
        against: string;
    };
    url: '/api/v1/entries/{entry_id}/versions/{version_id}/diff';
};

export type entriesDiffErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type entriesDiffError = entriesDiffErrors[keyof entriesDiffErrors];

export type entriesDiffResponses = {
    /**
     * Successful Response
     */
    200: DiffPublic;
};

export type entriesDiffResponse = entriesDiffResponses[keyof entriesDiffResponses];

export type entriesRevertData = {
    body?: never;
    headers?: {
        /**
         * If-Match
         */
        'If-Match'?: string | null;
    };
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
        /**
         * Version Id
         */
        version_id: string;
    };
    query?: never;
    url: '/api/v1/entries/{entry_id}/versions/{version_id}/revert';
};

export type entriesRevertErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type entriesRevertError = entriesRevertErrors[keyof entriesRevertErrors];

export type entriesRevertResponses = {
    /**
     * Response Entries-Revert
     *
     * Successful Response
     */
    200: EntryPublic | PatientTimelineEntry;
};

export type entriesRevertResponse = entriesRevertResponses[keyof entriesRevertResponses];

export type collaborationListCommentsData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/entries/{entry_id}/comments';
};

export type collaborationListCommentsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collaborationListCommentsError = collaborationListCommentsErrors[keyof collaborationListCommentsErrors];

export type collaborationListCommentsResponses = {
    /**
     * Response Collaboration-List Comments
     *
     * Successful Response
     */
    200: Array<CommentPublic>;
};

export type collaborationListCommentsResponse = collaborationListCommentsResponses[keyof collaborationListCommentsResponses];

export type collaborationCreateCommentData = {
    body: CommentCreate;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/entries/{entry_id}/comments';
};

export type collaborationCreateCommentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collaborationCreateCommentError = collaborationCreateCommentErrors[keyof collaborationCreateCommentErrors];

export type collaborationCreateCommentResponses = {
    /**
     * Successful Response
     */
    201: CommentPublic;
};

export type collaborationCreateCommentResponse = collaborationCreateCommentResponses[keyof collaborationCreateCommentResponses];

export type collaborationReplyData = {
    body: CommentCreate;
    path: {
        /**
         * Comment Id
         */
        comment_id: string;
    };
    query?: never;
    url: '/api/v1/comments/{comment_id}/replies';
};

export type collaborationReplyErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collaborationReplyError = collaborationReplyErrors[keyof collaborationReplyErrors];

export type collaborationReplyResponses = {
    /**
     * Successful Response
     */
    201: CommentPublic;
};

export type collaborationReplyResponse = collaborationReplyResponses[keyof collaborationReplyResponses];

export type collaborationResolveData = {
    body?: never;
    path: {
        /**
         * Comment Id
         */
        comment_id: string;
    };
    query?: never;
    url: '/api/v1/comments/{comment_id}/resolve';
};

export type collaborationResolveErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collaborationResolveError = collaborationResolveErrors[keyof collaborationResolveErrors];

export type collaborationResolveResponses = {
    /**
     * Successful Response
     */
    200: CommentPublic;
};

export type collaborationResolveResponse = collaborationResolveResponses[keyof collaborationResolveResponses];

export type collaborationAssignData = {
    body: AssignmentUpdate;
    path: {
        /**
         * Comment Id
         */
        comment_id: string;
    };
    query?: never;
    url: '/api/v1/comments/{comment_id}/assignment';
};

export type collaborationAssignErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collaborationAssignError = collaborationAssignErrors[keyof collaborationAssignErrors];

export type collaborationAssignResponses = {
    /**
     * Successful Response
     */
    200: CommentPublic;
};

export type collaborationAssignResponse = collaborationAssignResponses[keyof collaborationAssignResponses];

export type trustCreateHighlightData = {
    body: HighlightCreate;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/entries/{entry_id}/highlights';
};

export type trustCreateHighlightErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustCreateHighlightError = trustCreateHighlightErrors[keyof trustCreateHighlightErrors];

export type trustCreateHighlightResponses = {
    /**
     * Successful Response
     */
    201: HighlightPublic;
};

export type trustCreateHighlightResponse = trustCreateHighlightResponses[keyof trustCreateHighlightResponses];

export type trustAcceptData = {
    body?: never;
    path: {
        /**
         * Highlight Id
         */
        highlight_id: string;
    };
    query?: never;
    url: '/api/v1/highlights/{highlight_id}/accept';
};

export type trustAcceptErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustAcceptError = trustAcceptErrors[keyof trustAcceptErrors];

export type trustAcceptResponses = {
    /**
     * Successful Response
     */
    200: HighlightPublic;
};

export type trustAcceptResponse = trustAcceptResponses[keyof trustAcceptResponses];

export type trustRejectData = {
    body?: never;
    path: {
        /**
         * Highlight Id
         */
        highlight_id: string;
    };
    query?: never;
    url: '/api/v1/highlights/{highlight_id}/reject';
};

export type trustRejectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustRejectError = trustRejectErrors[keyof trustRejectErrors];

export type trustRejectResponses = {
    /**
     * Successful Response
     */
    200: HighlightPublic;
};

export type trustRejectResponse = trustRejectResponses[keyof trustRejectResponses];

export type trustPinData = {
    body?: never;
    path: {
        /**
         * Highlight Id
         */
        highlight_id: string;
    };
    query?: never;
    url: '/api/v1/highlights/{highlight_id}/pin';
};

export type trustPinErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustPinError = trustPinErrors[keyof trustPinErrors];

export type trustPinResponses = {
    /**
     * Successful Response
     */
    200: HighlightPublic;
};

export type trustPinResponse = trustPinResponses[keyof trustPinResponses];

export type trustProvenanceResolveData = {
    body?: never;
    path: {
        /**
         * Pointer Id
         */
        pointer_id: string;
    };
    query?: never;
    url: '/api/v1/provenance/{pointer_id}/resolve';
};

export type trustProvenanceResolveErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustProvenanceResolveError = trustProvenanceResolveErrors[keyof trustProvenanceResolveErrors];

export type trustProvenanceResolveResponses = {
    /**
     * Successful Response
     */
    200: ProvenanceResolved;
};

export type trustProvenanceResolveResponse = trustProvenanceResolveResponses[keyof trustProvenanceResolveResponses];

export type eventsEventStreamData = {
    body?: never;
    headers?: {
        /**
         * Last-Event-Id
         */
        'Last-Event-ID'?: number | null;
    };
    path?: never;
    query?: {
        /**
         * Snapshot
         */
        snapshot?: boolean;
    };
    url: '/api/v1/events/stream';
};

export type eventsEventStreamErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsEventStreamError = eventsEventStreamErrors[keyof eventsEventStreamErrors];

export type eventsEventStreamResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
