// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AIIngestRequest
 */
export type AIIngestRequest = {
    /**
     * Source Entry Version Id
     */
    source_entry_version_id: string;
    /**
     * Interaction Type
     */
    interaction_type?: 'care_note' | 'doctor_consult' | 'patient_insight' | 'voice_session';
};

/**
 * AIRunPublic
 */
export type AIRunPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Source Entry Version Id
     */
    source_entry_version_id: string;
    /**
     * Provider
     */
    provider: string;
    /**
     * Model
     */
    model: string;
    /**
     * Review Model
     */
    review_model: string | null;
    /**
     * Review Status
     */
    review_status: string;
    /**
     * Status
     */
    status: string;
    /**
     * Risk Tier
     */
    risk_tier: string;
    /**
     * Fallback Reason
     */
    fallback_reason: string | null;
    /**
     * Needs Review
     */
    needs_review: boolean;
    /**
     * Output Entry Id
     */
    output_entry_id: string | null;
    /**
     * Output Entry Version Id
     */
    output_entry_version_id: string | null;
    /**
     * Warnings
     */
    warnings: Array<string>;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * AssignmentUpdate
 */
export type AssignmentUpdate = {
    /**
     * Assigned Membership Id
     */
    assigned_membership_id: string | null;
};

/**
 * AudioChunkAck
 */
export type AudioChunkAck = {
    /**
     * Chunk Index
     */
    chunk_index: number;
    /**
     * Acknowledged
     */
    acknowledged?: boolean;
    /**
     * Duplicate
     */
    duplicate?: boolean;
};

/**
 * AuditEventPublic
 */
export type AuditEventPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Actor Id
     */
    actor_id: string;
    /**
     * Action
     */
    action: string;
    /**
     * Resource Type
     */
    resource_type: string;
    /**
     * Resource Id
     */
    resource_id: string;
    /**
     * Version Id
     */
    version_id: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * AuditEventsPublic
 */
export type AuditEventsPublic = {
    /**
     * Data
     */
    data: Array<AuditEventPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Body_auth-password_login
 */
export type Body_auth_password_login = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ClinicAISettingPublic
 */
export type ClinicAISettingPublic = {
    /**
     * Provider
     */
    provider?: 'openai';
    /**
     * Api Key Configured
     */
    api_key_configured: boolean;
    /**
     * Api Key Last4
     */
    api_key_last4: string | null;
    /**
     * Credential Source
     */
    credential_source: 'clinic' | 'environment' | 'none';
    /**
     * Fast Model
     */
    fast_model: string;
    /**
     * Careful Model
     */
    careful_model: string;
    /**
     * Transcribe Model
     */
    transcribe_model: string;
    /**
     * Updated At
     */
    updated_at: string | null;
};

/**
 * ClinicAISettingUpdate
 */
export type ClinicAISettingUpdate = {
    /**
     * Api Key
     */
    api_key?: string | null;
    /**
     * Clear Api Key
     */
    clear_api_key?: boolean;
    /**
     * Fast Model
     */
    fast_model: string;
    /**
     * Careful Model
     */
    careful_model: string;
    /**
     * Transcribe Model
     */
    transcribe_model: string;
};

/**
 * ClinicalFactAssertionPublic
 */
export type ClinicalFactAssertionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Fact Type
     */
    fact_type: string;
    /**
     * Subject
     */
    subject: string;
    /**
     * Normalized Value
     */
    normalized_value: string;
    /**
     * Clinical Status
     */
    clinical_status: string;
    /**
     * Effective Time
     */
    effective_time: string | null;
    /**
     * Origin
     */
    origin: string;
    /**
     * Source Entry Version Id
     */
    source_entry_version_id: string;
    /**
     * Provenance Pointer Id
     */
    provenance_pointer_id: string;
};

/**
 * ClinicalFactPublic
 */
export type ClinicalFactPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Ordinal
     */
    ordinal: number;
    /**
     * Fact Type
     */
    fact_type: string;
    /**
     * Value
     */
    value: string;
    /**
     * Exact Quote
     */
    exact_quote: string;
    /**
     * Transcript Start
     */
    transcript_start: number;
    /**
     * Transcript End
     */
    transcript_end: number;
    /**
     * Audio Asset Id
     */
    audio_asset_id: string;
    /**
     * Audio Start Ms
     */
    audio_start_ms: number;
    /**
     * Audio End Ms
     */
    audio_end_ms: number;
    /**
     * Status
     */
    status: string;
    /**
     * Stale
     */
    stale: boolean;
};

/**
 * ClinicalGlanceCard
 */
export type ClinicalGlanceCard = {
    /**
     * Highlight Id
     */
    highlight_id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Critical
     */
    critical: boolean;
    /**
     * Pinned
     */
    pinned: boolean;
    /**
     * Risk Reason
     */
    risk_reason: string;
    /**
     * Provenance Pointer Id
     */
    provenance_pointer_id: string;
    /**
     * Score Components
     */
    score_components: {
        [key: string]: number;
    };
    /**
     * Review State
     */
    review_state?: 'ready' | 'review_required' | 'abstained';
    /**
     * Risk
     */
    risk?: {
        [key: string]: unknown;
    };
    /**
     * Confidence
     */
    confidence?: {
        [key: string]: unknown;
    };
    /**
     * Importance
     */
    importance?: {
        [key: string]: unknown;
    };
    /**
     * Abstention Reason
     */
    abstention_reason?: string | null;
};

/**
 * ClinicalGlancePublic
 */
export type ClinicalGlancePublic = {
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Source
     */
    source?: 'precomputed';
    /**
     * Generated At
     */
    generated_at: string;
    /**
     * Cards
     */
    cards: Array<ClinicalGlanceCard>;
    /**
     * Review Cards
     */
    review_cards?: Array<ClinicalGlanceCard>;
};

/**
 * CommentCreate
 */
export type CommentCreate = {
    /**
     * Entry Version Id
     */
    entry_version_id: string;
    /**
     * Start Offset
     */
    start_offset: number;
    /**
     * End Offset
     */
    end_offset: number;
    /**
     * Exact Quote
     */
    exact_quote: string;
    /**
     * Prefix
     */
    prefix?: string;
    /**
     * Suffix
     */
    suffix?: string;
    /**
     * Body
     */
    body: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Mentioned User Ids
     */
    mentioned_user_ids?: Array<string>;
    /**
     * Assigned Membership Id
     */
    assigned_membership_id?: string | null;
};

/**
 * CommentPublic
 */
export type CommentPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Entry Id
     */
    entry_id: string;
    /**
     * Entry Version Id
     */
    entry_version_id: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Body
     */
    body: string;
    /**
     * Anchor State
     */
    anchor_state: string;
    /**
     * Review Required
     */
    review_required: boolean;
    /**
     * Assigned Membership Id
     */
    assigned_membership_id: string | null;
    /**
     * Mentioned User Ids
     */
    mentioned_user_ids?: Array<string>;
    /**
     * Resolved At
     */
    resolved_at: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ConflictPublic
 */
export type ConflictPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Fact Type
     */
    fact_type: string;
    /**
     * Normalized Key
     */
    normalized_key: string;
    /**
     * Severity
     */
    severity: string;
    /**
     * Status
     */
    status: string;
    /**
     * Left Entry Id
     */
    left_entry_id: string;
    /**
     * Right Entry Id
     */
    right_entry_id: string;
    /**
     * Left Pointer Id
     */
    left_pointer_id: string | null;
    /**
     * Right Pointer Id
     */
    right_pointer_id: string | null;
    /**
     * Resolution
     */
    resolution: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ConflictResolve
 */
export type ConflictResolve = {
    /**
     * Resolution
     */
    resolution: string;
    /**
     * Correction Entry Id
     */
    correction_entry_id: string;
};

/**
 * DecayArchivePublic
 */
export type DecayArchivePublic = {
    /**
     * Decay Run Id
     */
    decay_run_id: string;
    /**
     * Candidate Count
     */
    candidate_count: number;
    /**
     * Archived Count
     */
    archived_count: number;
    /**
     * Error Count
     */
    error_count: number;
};

/**
 * DecayArchiveRequest
 */
export type DecayArchiveRequest = {
    /**
     * Entry Version Ids
     */
    entry_version_ids?: Array<string>;
    /**
     * Dry Run
     */
    dry_run?: boolean;
};

/**
 * DecayCandidatePublic
 */
export type DecayCandidatePublic = {
    /**
     * Entry Version Id
     */
    entry_version_id: string;
    /**
     * Entry Id
     */
    entry_id: string;
    /**
     * Storage Tier
     */
    storage_tier: 'hot' | 'warm' | 'cold';
    /**
     * Age Days
     */
    age_days: number;
    /**
     * Eligible For Cold
     */
    eligible_for_cold: boolean;
    /**
     * Protected Reasons
     */
    protected_reasons: Array<string>;
};

/**
 * DecayPreviewPublic
 */
export type DecayPreviewPublic = {
    /**
     * Policy Version
     */
    policy_version?: string;
    /**
     * Candidates
     */
    candidates: Array<DecayCandidatePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * DecisionExplanationPublic
 */
export type DecisionExplanationPublic = {
    /**
     * Highlight Id
     */
    highlight_id: string;
    /**
     * Review State
     */
    review_state: 'ready' | 'review_required' | 'abstained';
    /**
     * Output Type
     */
    output_type: string;
    /**
     * Support State
     */
    support_state: string;
    /**
     * Risk
     */
    risk: {
        [key: string]: unknown;
    };
    /**
     * Confidence
     */
    confidence: {
        [key: string]: unknown;
    };
    /**
     * Importance
     */
    importance: {
        [key: string]: unknown;
    };
    /**
     * Abstention Reason
     */
    abstention_reason: string | null;
};

/**
 * DemoLoginRequest
 */
export type DemoLoginRequest = {
    /**
     * Persona
     */
    persona: 'patient' | 'staff' | 'clinician' | 'admin' | 'worker' | 'other_staff';
};

/**
 * DiffPublic
 */
export type DiffPublic = {
    /**
     * From Version Id
     */
    from_version_id: string;
    /**
     * To Version Id
     */
    to_version_id: string;
    /**
     * Unified Diff
     */
    unified_diff: string;
};

/**
 * EntryCreate
 */
export type EntryCreate = {
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Section
     */
    section: 'patient' | 'staff' | 'clinician' | 'system';
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * Patient Facing
     */
    patient_facing?: boolean;
    /**
     * Origin
     */
    origin?: 'human' | 'ai' | 'system';
    /**
     * Entry Type
     */
    entry_type?: 'manual_staff_note' | 'manual_clinician_note' | 'manual_patient_insight' | 'ai_doctor_consult_summary' | 'ai_nurse_consult_summary' | 'ai_patient_session_summary' | 'voice_transcript_source' | 'voice_reviewed_result' | 'legacy_review_required' | 'system_record' | null;
    /**
     * Occurred At
     */
    occurred_at?: string | null;
    /**
     * Supersedes Entry Id
     */
    supersedes_entry_id?: string | null;
    /**
     * Conflicts With Entry Id
     */
    conflicts_with_entry_id?: string | null;
};

/**
 * EntryPatch
 */
export type EntryPatch = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Patient Facing
     */
    patient_facing?: boolean | null;
};

/**
 * EntryPublic
 */
export type EntryPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Clinic Id
     */
    clinic_id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Section
     */
    section: string;
    /**
     * Origin
     */
    origin: string;
    /**
     * Entry Type
     */
    entry_type: 'manual_staff_note' | 'manual_clinician_note' | 'manual_patient_insight' | 'ai_doctor_consult_summary' | 'ai_nurse_consult_summary' | 'ai_patient_session_summary' | 'voice_transcript_source' | 'voice_reviewed_result' | 'legacy_review_required' | 'system_record';
    /**
     * Patient Facing
     */
    patient_facing: boolean;
    /**
     * Version Id
     */
    version_id: string;
    /**
     * Version No
     */
    version_no: number;
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Occurred At
     */
    occurred_at: string;
};

/**
 * EntryVersionPublic
 */
export type EntryVersionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Entry Id
     */
    entry_id: string;
    /**
     * Version No
     */
    version_no: number;
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * Content Sha256
     */
    content_sha256: string;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Reverted From Version Id
     */
    reverted_from_version_id: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * EntryVersionsPublic
 */
export type EntryVersionsPublic = {
    /**
     * Data
     */
    data: Array<EntryVersionPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * GlancePublic
 */
export type GlancePublic = {
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Source
     */
    source?: 'precomputed';
    /**
     * Generated At
     */
    generated_at: string;
    /**
     * Cards
     */
    cards: Array<PatientGlanceCard>;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HighlightCreate
 */
export type HighlightCreate = {
    /**
     * Entry Version Id
     */
    entry_version_id: string;
    /**
     * Start Offset
     */
    start_offset: number;
    /**
     * End Offset
     */
    end_offset: number;
    /**
     * Exact Quote
     */
    exact_quote: string;
    /**
     * Prefix
     */
    prefix?: string;
    /**
     * Suffix
     */
    suffix?: string;
    /**
     * Label
     */
    label: string;
    /**
     * Critical
     */
    critical?: boolean;
    /**
     * Patient Facing
     */
    patient_facing?: boolean;
    /**
     * Feature Keys
     */
    feature_keys?: Array<string>;
    /**
     * Unresolved
     */
    unresolved?: boolean;
    /**
     * Clinician Confirmed
     */
    clinician_confirmed?: boolean;
};

/**
 * HighlightPublic
 */
export type HighlightPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Entry Id
     */
    entry_id: string;
    /**
     * Source Entry Version Id
     */
    source_entry_version_id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Status
     */
    status: string;
    /**
     * Pinned
     */
    pinned: boolean;
    /**
     * Critical
     */
    critical: boolean;
    /**
     * Patient Facing
     */
    patient_facing: boolean;
    /**
     * Anchor State
     */
    anchor_state: string;
    /**
     * Review Required
     */
    review_required: boolean;
    /**
     * Feature Keys
     */
    feature_keys: Array<string>;
    /**
     * Base Score
     */
    base_score: number;
    /**
     * Learned Score
     */
    learned_score: number;
    /**
     * Final Score
     */
    final_score: number;
    /**
     * Risk Reason
     */
    risk_reason: string;
    /**
     * Unresolved
     */
    unresolved: boolean;
    /**
     * Clinician Confirmed
     */
    clinician_confirmed: boolean;
    /**
     * Provenance Pointer Id
     */
    provenance_pointer_id: string;
};

/**
 * ImportanceFeedbackCreate
 */
export type ImportanceFeedbackCreate = {
    /**
     * Signal
     */
    signal: 'dismiss';
    /**
     * Reason
     */
    reason: 'not_relevant' | 'outdated' | 'already_addressed' | 'too_busy_to_review';
};

/**
 * ImportanceImpressionCreate
 */
export type ImportanceImpressionCreate = {
    /**
     * Highlight Id
     */
    highlight_id: string;
    /**
     * View Event Id
     */
    view_event_id: string;
    /**
     * Rank
     */
    rank: number;
    /**
     * Surface
     */
    surface?: string;
    /**
     * Exposure Probability
     */
    exposure_probability?: number;
    /**
     * Visible Ratio
     */
    visible_ratio: number;
    /**
     * Visible Duration Ms
     */
    visible_duration_ms: number;
};

/**
 * JobPublic
 */
export type JobPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * State
     */
    state: string;
    /**
     * Attempt Count
     */
    attempt_count: number;
    /**
     * Max Attempts
     */
    max_attempts: number;
    /**
     * Error Code
     */
    error_code: string | null;
    ai_run?: AIRunPublic | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * LiveTranscriptAvailability
 */
export type LiveTranscriptAvailability = {
    /**
     * Available
     */
    available: boolean;
    /**
     * Status
     */
    status: 'available' | 'unavailable' | 'needs_review' | 'replaced';
    /**
     * Reason Code
     */
    reason_code?: string | null;
    /**
     * Provider
     */
    provider?: string | null;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Provisional
     */
    provisional?: true;
};

/**
 * MePublic
 */
export type MePublic = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * Clinic Id
     */
    clinic_id: string;
    /**
     * Clinic Code
     */
    clinic_code: string;
    /**
     * Clinic Name
     */
    clinic_name: string;
    /**
     * Membership Id
     */
    membership_id: string;
    /**
     * Role
     */
    role: 'patient' | 'staff' | 'clinician' | 'admin' | 'worker';
};

/**
 * MembershipCreate
 */
export type MembershipCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Role
     */
    role: 'staff' | 'clinician' | 'admin';
};

/**
 * MembershipInvitationAccept
 */
export type MembershipInvitationAccept = {
    /**
     * Email
     */
    email: string;
    /**
     * Token
     */
    token: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * MembershipInvitationPublic
 */
export type MembershipInvitationPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * Role
     */
    role: 'staff' | 'clinician' | 'admin';
    /**
     * State
     */
    state?: 'pending';
    /**
     * Expires At
     */
    expires_at: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * MembershipPublic
 */
export type MembershipPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * Role
     */
    role: 'patient' | 'staff' | 'clinician' | 'admin' | 'worker';
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * MembershipsPublic
 */
export type MembershipsPublic = {
    /**
     * Data
     */
    data: Array<MembershipPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * PatientCreate
 */
export type PatientCreate = {
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Date Of Birth
     */
    date_of_birth: string;
    /**
     * Medical Record Number
     */
    medical_record_number: string;
    /**
     * Identity Document Type
     */
    identity_document_type: 'nric_fin' | 'passport' | 'other';
    /**
     * Identity Document Number
     */
    identity_document_number: string;
    /**
     * Duplicate Confirmation Token
     */
    duplicate_confirmation_token?: string | null;
};

/**
 * PatientDetailPublic
 */
export type PatientDetailPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Date Of Birth
     */
    date_of_birth: string | null;
    /**
     * Medical Record Number
     */
    medical_record_number: string | null;
    /**
     * Same Name Count
     */
    same_name_count?: number;
    /**
     * Today Visit At
     */
    today_visit_at?: string | null;
    /**
     * Today Visit Status
     */
    today_visit_status?: string | null;
    /**
     * Today Visit Type
     */
    today_visit_type?: string | null;
    /**
     * Last Activity At
     */
    last_activity_at?: string | null;
    /**
     * Identity Document Type
     */
    identity_document_type: string | null;
    /**
     * Masked Identity Document
     */
    masked_identity_document: string | null;
    /**
     * Portal Access State
     */
    portal_access_state: 'not_invited' | 'pending' | 'active' | 'deactivated';
    /**
     * Status
     */
    status: string;
};

/**
 * PatientDuplicateCandidate
 */
export type PatientDuplicateCandidate = {
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Date Of Birth
     */
    date_of_birth: string | null;
    /**
     * Medical Record Number
     */
    medical_record_number: string | null;
    /**
     * Masked Identity Document
     */
    masked_identity_document: string | null;
};

/**
 * PatientDuplicateCheckPublic
 */
export type PatientDuplicateCheckPublic = {
    /**
     * Status
     */
    status: 'clear' | 'possible_match' | 'exact_match';
    /**
     * Candidates
     */
    candidates: Array<PatientDuplicateCandidate>;
    /**
     * Duplicate Confirmation Token
     */
    duplicate_confirmation_token?: string | null;
};

/**
 * PatientGlanceCard
 */
export type PatientGlanceCard = {
    /**
     * Highlight Id
     */
    highlight_id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Provenance Pointer Id
     */
    provenance_pointer_id: string;
};

/**
 * PatientIdentityInput
 */
export type PatientIdentityInput = {
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Date Of Birth
     */
    date_of_birth: string;
    /**
     * Medical Record Number
     */
    medical_record_number: string;
    /**
     * Identity Document Type
     */
    identity_document_type: 'nric_fin' | 'passport' | 'other';
    /**
     * Identity Document Number
     */
    identity_document_number: string;
};

/**
 * PatientInvitationAccept
 */
export type PatientInvitationAccept = {
    /**
     * Token
     */
    token: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * PatientInvitationPreviewPublic
 */
export type PatientInvitationPreviewPublic = {
    /**
     * Clinic Name
     */
    clinic_name: string;
    /**
     * Patient Display Name
     */
    patient_display_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Account Exists
     */
    account_exists: boolean;
};

/**
 * PatientInvitationPreviewRequest
 */
export type PatientInvitationPreviewRequest = {
    /**
     * Token
     */
    token: string;
    /**
     * Email
     */
    email: string;
};

/**
 * PatientPortalInvitationCreate
 */
export type PatientPortalInvitationCreate = {
    /**
     * Email
     */
    email: string;
};

/**
 * PatientPortalInvitationPublic
 */
export type PatientPortalInvitationPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Email
     */
    email: string;
    /**
     * State
     */
    state?: 'pending';
    /**
     * Expires At
     */
    expires_at: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PatientPublic
 */
export type PatientPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Date Of Birth
     */
    date_of_birth?: string | null;
    /**
     * Medical Record Number
     */
    medical_record_number?: string | null;
    /**
     * Same Name Count
     */
    same_name_count?: number;
    /**
     * Today Visit At
     */
    today_visit_at?: string | null;
    /**
     * Today Visit Status
     */
    today_visit_status?: string | null;
    /**
     * Today Visit Type
     */
    today_visit_type?: string | null;
    /**
     * Last Activity At
     */
    last_activity_at?: string | null;
};

/**
 * PatientPublicationCreate
 */
export type PatientPublicationCreate = {
    /**
     * Entry Version Id
     */
    entry_version_id: string;
};

/**
 * PatientPublicationPublic
 */
export type PatientPublicationPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Entry Version Id
     */
    entry_version_id: string;
    /**
     * Approved By Name
     */
    approved_by_name: string;
    /**
     * Approval Policy Version
     */
    approval_policy_version: string;
    /**
     * Approved At
     */
    approved_at: string;
    /**
     * Withdrawn At
     */
    withdrawn_at: string | null;
    /**
     * Items
     */
    items?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * PatientSharingRequestCreate
 */
export type PatientSharingRequestCreate = {
    /**
     * Entry Version Id
     */
    entry_version_id: string;
};

/**
 * PatientSharingRequestPublic
 */
export type PatientSharingRequestPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Entry Id
     */
    entry_id: string;
    /**
     * Entry Version Id
     */
    entry_version_id: string;
    /**
     * Requested By Name
     */
    requested_by_name: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Reviewed At
     */
    reviewed_at: string | null;
};

/**
 * PatientTimeline
 */
export type PatientTimeline = {
    /**
     * Data
     */
    data: Array<PatientTimelineEntry>;
    /**
     * Count
     */
    count: number;
};

/**
 * PatientTimelineEntry
 */
export type PatientTimelineEntry = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Section
     */
    section: string;
    /**
     * Entry Type
     */
    entry_type: 'manual_staff_note' | 'manual_clinician_note' | 'manual_patient_insight' | 'ai_doctor_consult_summary' | 'ai_nurse_consult_summary' | 'ai_patient_session_summary' | 'voice_transcript_source' | 'voice_reviewed_result' | 'legacy_review_required' | 'system_record';
    /**
     * Patient Facing
     */
    patient_facing: boolean;
    /**
     * Version Id
     */
    version_id: string;
    /**
     * Version No
     */
    version_no: number;
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Approval Receipt
     */
    approval_receipt?: {
        [key: string]: unknown;
    } | null;
};

/**
 * PatientsPublic
 */
export type PatientsPublic = {
    /**
     * Data
     */
    data: Array<PatientPublic>;
    /**
     * Count
     */
    count: number;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
};

/**
 * PlatformAuditPublic
 */
export type PlatformAuditPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Action
     */
    action: string;
    /**
     * Target Clinic Id
     */
    target_clinic_id: string | null;
    /**
     * Target Patient Id
     */
    target_patient_id: string | null;
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PlatformAuditsPublic
 */
export type PlatformAuditsPublic = {
    /**
     * Data
     */
    data: Array<PlatformAuditPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PlatformClinicPublic
 */
export type PlatformClinicPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Member Count
     */
    member_count: number;
    /**
     * Patient Count
     */
    patient_count: number;
};

/**
 * PlatformClinicsPublic
 */
export type PlatformClinicsPublic = {
    /**
     * Data
     */
    data: Array<PlatformClinicPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PlatformLogin
 */
export type PlatformLogin = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * PlatformMePublic
 */
export type PlatformMePublic = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Platform Admin Id
     */
    platform_admin_id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * Role
     */
    role?: 'platform_admin';
};

/**
 * ProvenanceResolved
 */
export type ProvenanceResolved = {
    /**
     * Id
     */
    id: string;
    /**
     * Entry Version Id
     */
    entry_version_id: string;
    /**
     * State
     */
    state: string;
    /**
     * Review Required
     */
    review_required: boolean;
    /**
     * Start Offset
     */
    start_offset: number;
    /**
     * End Offset
     */
    end_offset: number;
    /**
     * Exact Quote
     */
    exact_quote: string;
    /**
     * Prefix
     */
    prefix: string;
    /**
     * Suffix
     */
    suffix: string;
    /**
     * Quote Sha256
     */
    quote_sha256: string;
    /**
     * Audio Asset Id
     */
    audio_asset_id: string | null;
    /**
     * Audio Start Ms
     */
    audio_start_ms: number | null;
    /**
     * Audio End Ms
     */
    audio_end_ms: number | null;
};

/**
 * RehydratePublic
 */
export type RehydratePublic = {
    /**
     * Entry Version Id
     */
    entry_version_id: string;
    /**
     * Storage Tier
     */
    storage_tier: string;
    /**
     * Content Sha256
     */
    content_sha256: string;
};

/**
 * ReviewRequestCreate
 */
export type ReviewRequestCreate = {
    /**
     * Reason
     */
    reason: string;
};

/**
 * TeamMemberPublic
 */
export type TeamMemberPublic = {
    /**
     * Membership Id
     */
    membership_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * Role
     */
    role: 'staff' | 'clinician' | 'admin';
};

/**
 * TeamMembersPublic
 */
export type TeamMembersPublic = {
    /**
     * Data
     */
    data: Array<TeamMemberPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * TranscriptCorrection
 */
export type TranscriptCorrection = {
    /**
     * Expected Revision Id
     */
    expected_revision_id: string;
    /**
     * Text
     */
    text: string;
};

/**
 * TranscriptRevisionPublic
 */
export type TranscriptRevisionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Revision No
     */
    revision_no: number;
    /**
     * Previous Revision Id
     */
    previous_revision_id: string | null;
    /**
     * Text
     */
    text: string;
    /**
     * Text Sha256
     */
    text_sha256: string;
    /**
     * Summary
     */
    summary: string | null;
    /**
     * Provider
     */
    provider: string;
    /**
     * Model
     */
    model: string;
    /**
     * Detected Language
     */
    detected_language: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Needs Review
     */
    needs_review: boolean;
    /**
     * Stale
     */
    stale: boolean;
    /**
     * Fallback
     */
    fallback: boolean;
    /**
     * Warning Codes
     */
    warning_codes: Array<string>;
    /**
     * Segments
     */
    segments: Array<TranscriptSegmentPublic>;
    /**
     * Facts
     */
    facts: Array<ClinicalFactPublic>;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * TranscriptSegmentPublic
 */
export type TranscriptSegmentPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Ordinal
     */
    ordinal: number;
    /**
     * Text
     */
    text: string;
    /**
     * Text Start
     */
    text_start: number;
    /**
     * Text End
     */
    text_end: number;
    /**
     * Start Ms
     */
    start_ms: number;
    /**
     * End Ms
     */
    end_ms: number;
    /**
     * Speaker Id
     */
    speaker_id: string | null;
    /**
     * Detected Language
     */
    detected_language: string | null;
    /**
     * Confidence
     */
    confidence: number | null;
    /**
     * Confidence Source
     */
    confidence_source: string;
    /**
     * Overlap Group Id
     */
    overlap_group_id: string | null;
    /**
     * Provider
     */
    provider: string;
    /**
     * Model
     */
    model: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VoiceChunkStatus
 */
export type VoiceChunkStatus = {
    /**
     * Uploaded Chunks
     */
    uploaded_chunks: number;
    /**
     * Devices
     */
    devices: Array<VoiceDeviceChunkStatus>;
};

/**
 * VoiceDeviceAbandonPublic
 */
export type VoiceDeviceAbandonPublic = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Abandoned
     */
    abandoned?: true;
};

/**
 * VoiceDeviceChunkStatus
 */
export type VoiceDeviceChunkStatus = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Client Device Id
     */
    client_device_id: string;
    /**
     * Received Indices
     */
    received_indices: Array<number>;
    /**
     * Last Declared Chunk Index
     */
    last_declared_chunk_index: number | null;
};

/**
 * VoiceDeviceJoin
 */
export type VoiceDeviceJoin = {
    /**
     * Client Device Id
     */
    client_device_id: string;
    /**
     * Capture Role
     */
    capture_role: 'patient' | 'staff' | 'clinician';
    /**
     * Expected Patient Id
     */
    expected_patient_id: string;
    /**
     * Expected Capture Kind
     */
    expected_capture_kind: 'patient' | 'clinical';
};

/**
 * VoiceDevicePublic
 */
export type VoiceDevicePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Client Device Id
     */
    client_device_id: string;
    /**
     * Capture Role
     */
    capture_role: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * VoiceDeviceSeal
 */
export type VoiceDeviceSeal = {
    /**
     * Last Chunk Index
     */
    last_chunk_index: number;
};

/**
 * VoiceDeviceSealPublic
 */
export type VoiceDeviceSealPublic = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Last Chunk Index
     */
    last_chunk_index: number;
    /**
     * Sealed
     */
    sealed?: true;
};

/**
 * VoiceFinalizeDevice
 */
export type VoiceFinalizeDevice = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Last Chunk Index
     */
    last_chunk_index: number;
};

/**
 * VoiceFinalizePublic
 */
export type VoiceFinalizePublic = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * State
     */
    state: string;
    /**
     * Job Id
     */
    job_id: string;
};

/**
 * VoiceFinalizeRequest
 */
export type VoiceFinalizeRequest = {
    /**
     * Devices
     */
    devices: Array<VoiceFinalizeDevice>;
};

/**
 * VoicePublishPublic
 */
export type VoicePublishPublic = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Entry Id
     */
    entry_id: string;
    /**
     * Entry Version Id
     */
    entry_version_id: string;
    /**
     * State
     */
    state?: 'published';
};

/**
 * VoicePublishRequest
 */
export type VoicePublishRequest = {
    /**
     * Expected Revision Id
     */
    expected_revision_id: string;
};

/**
 * VoiceReanalyzePublic
 */
export type VoiceReanalyzePublic = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Job Id
     */
    job_id: string;
    /**
     * State
     */
    state: string;
};

/**
 * VoiceReanalyzeRequest
 */
export type VoiceReanalyzeRequest = {
    /**
     * Expected Revision Id
     */
    expected_revision_id: string;
};

/**
 * VoiceSessionCreate
 */
export type VoiceSessionCreate = {
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Capture Kind
     */
    capture_kind: 'patient' | 'clinical';
    /**
     * Synthetic Fixture
     */
    synthetic_fixture?: boolean;
    /**
     * Fixture Id
     */
    fixture_id?: string | null;
};

/**
 * VoiceSessionPublic
 */
export type VoiceSessionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Capture Kind
     */
    capture_kind: string;
    /**
     * State
     */
    state: string;
    /**
     * Patient Summary
     */
    patient_summary?: string | null;
    /**
     * Warning Codes
     */
    warning_codes?: Array<string>;
    /**
     * Error Code
     */
    error_code?: string | null;
    /**
     * Live Transcript Status
     */
    live_transcript_status?: 'not_started' | 'available' | 'unavailable' | 'needs_review' | 'replaced';
    /**
     * Live Transcript Reason Code
     */
    live_transcript_reason_code?: string | null;
    /**
     * Current Transcript Revision Id
     */
    current_transcript_revision_id?: string | null;
    /**
     * Published Entry Id
     */
    published_entry_id?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

export type authDemoLoginData = {
    body: DemoLoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/demo-login';
};

export type authDemoLoginErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authDemoLoginError = authDemoLoginErrors[keyof authDemoLoginErrors];

export type authDemoLoginResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type authDemoLoginResponse = authDemoLoginResponses[keyof authDemoLoginResponses];

export type authPasswordLoginData = {
    body: Body_auth_password_login;
    headers: {
        /**
         * X-Clinic-Code
         */
        'X-Clinic-Code': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type authPasswordLoginErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authPasswordLoginError = authPasswordLoginErrors[keyof authPasswordLoginErrors];

export type authPasswordLoginResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type authPasswordLoginResponse = authPasswordLoginResponses[keyof authPasswordLoginResponses];

export type authAcceptMembershipInvitationData = {
    body: MembershipInvitationAccept;
    path?: never;
    query?: never;
    url: '/api/v1/auth/invitations/accept';
};

export type authAcceptMembershipInvitationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authAcceptMembershipInvitationError = authAcceptMembershipInvitationErrors[keyof authAcceptMembershipInvitationErrors];

export type authAcceptMembershipInvitationResponses = {
    /**
     * Successful Response
     */
    200: MembershipPublic;
};

export type authAcceptMembershipInvitationResponse = authAcceptMembershipInvitationResponses[keyof authAcceptMembershipInvitationResponses];

export type authMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type authMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authMeError = authMeErrors[keyof authMeErrors];

export type authMeResponses = {
    /**
     * Successful Response
     */
    200: MePublic;
};

export type authMeResponse = authMeResponses[keyof authMeResponses];

export type authLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type authLogoutResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type authLogoutResponse = authLogoutResponses[keyof authLogoutResponses];

export type adminAiSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/ai-settings';
};

export type adminAiSettingsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAiSettingsError = adminAiSettingsErrors[keyof adminAiSettingsErrors];

export type adminAiSettingsResponses = {
    /**
     * Successful Response
     */
    200: ClinicAISettingPublic;
};

export type adminAiSettingsResponse = adminAiSettingsResponses[keyof adminAiSettingsResponses];

export type adminUpdateAiSettingsData = {
    body: ClinicAISettingUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/ai-settings';
};

export type adminUpdateAiSettingsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminUpdateAiSettingsError = adminUpdateAiSettingsErrors[keyof adminUpdateAiSettingsErrors];

export type adminUpdateAiSettingsResponses = {
    /**
     * Successful Response
     */
    200: ClinicAISettingPublic;
};

export type adminUpdateAiSettingsResponse = adminUpdateAiSettingsResponses[keyof adminUpdateAiSettingsResponses];

export type adminMembershipsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/memberships';
};

export type adminMembershipsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminMembershipsError = adminMembershipsErrors[keyof adminMembershipsErrors];

export type adminMembershipsResponses = {
    /**
     * Successful Response
     */
    200: MembershipsPublic;
};

export type adminMembershipsResponse = adminMembershipsResponses[keyof adminMembershipsResponses];

export type adminCreateMembershipData = {
    body: MembershipCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/memberships';
};

export type adminCreateMembershipErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminCreateMembershipError = adminCreateMembershipErrors[keyof adminCreateMembershipErrors];

export type adminCreateMembershipResponses = {
    /**
     * Successful Response
     */
    201: MembershipInvitationPublic;
};

export type adminCreateMembershipResponse = adminCreateMembershipResponses[keyof adminCreateMembershipResponses];

export type adminDeactivateMembershipData = {
    body?: never;
    path: {
        /**
         * Membership Id
         */
        membership_id: string;
    };
    query?: never;
    url: '/api/v1/admin/memberships/{membership_id}/deactivate';
};

export type adminDeactivateMembershipErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminDeactivateMembershipError = adminDeactivateMembershipErrors[keyof adminDeactivateMembershipErrors];

export type adminDeactivateMembershipResponses = {
    /**
     * Successful Response
     */
    200: MembershipPublic;
};

export type adminDeactivateMembershipResponse = adminDeactivateMembershipResponses[keyof adminDeactivateMembershipResponses];

export type adminAuditEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/audit';
};

export type adminAuditEventsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAuditEventsError = adminAuditEventsErrors[keyof adminAuditEventsErrors];

export type adminAuditEventsResponses = {
    /**
     * Successful Response
     */
    200: AuditEventsPublic;
};

export type adminAuditEventsResponse = adminAuditEventsResponses[keyof adminAuditEventsResponses];

export type aiIngestData = {
    body: AIIngestRequest;
    headers: {
        /**
         * Idempotency-Key
         */
        'Idempotency-Key': string;
    };
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/patients/{patient_id}/ai/ingest';
};

export type aiIngestErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type aiIngestError = aiIngestErrors[keyof aiIngestErrors];

export type aiIngestResponses = {
    /**
     * Successful Response
     */
    200: JobPublic;
};

export type aiIngestResponse = aiIngestResponses[keyof aiIngestResponses];

export type aiReanalyzeData = {
    body: AIIngestRequest;
    headers: {
        /**
         * Idempotency-Key
         */
        'Idempotency-Key': string;
    };
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/patients/{patient_id}/ai/reanalyze';
};

export type aiReanalyzeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type aiReanalyzeError = aiReanalyzeErrors[keyof aiReanalyzeErrors];

export type aiReanalyzeResponses = {
    /**
     * Successful Response
     */
    200: JobPublic;
};

export type aiReanalyzeResponse = aiReanalyzeResponses[keyof aiReanalyzeResponses];

export type aiGetJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/jobs/{job_id}';
};

export type aiGetJobErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type aiGetJobError = aiGetJobErrors[keyof aiGetJobErrors];

export type aiGetJobResponses = {
    /**
     * Successful Response
     */
    200: JobPublic;
};

export type aiGetJobResponse = aiGetJobResponses[keyof aiGetJobResponses];

export type aiRetryJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/jobs/{job_id}/retry';
};

export type aiRetryJobErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type aiRetryJobError = aiRetryJobErrors[keyof aiRetryJobErrors];

export type aiRetryJobResponses = {
    /**
     * Successful Response
     */
    200: JobPublic;
};

export type aiRetryJobResponse = aiRetryJobResponses[keyof aiRetryJobResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type patientsDuplicateCheckData = {
    body: PatientIdentityInput;
    path?: never;
    query?: never;
    url: '/api/v1/patients/duplicate-check';
};

export type patientsDuplicateCheckErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsDuplicateCheckError = patientsDuplicateCheckErrors[keyof patientsDuplicateCheckErrors];

export type patientsDuplicateCheckResponses = {
    /**
     * Successful Response
     */
    200: PatientDuplicateCheckPublic;
};

export type patientsDuplicateCheckResponse = patientsDuplicateCheckResponses[keyof patientsDuplicateCheckResponses];

export type patientsPatientsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search
         */
        search?: string | null;
        /**
         * Visit Scope
         */
        visit_scope?: 'all' | 'today' | 'previous';
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/patients';
};

export type patientsPatientsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsPatientsError = patientsPatientsErrors[keyof patientsPatientsErrors];

export type patientsPatientsResponses = {
    /**
     * Successful Response
     */
    200: PatientsPublic;
};

export type patientsPatientsResponse = patientsPatientsResponses[keyof patientsPatientsResponses];

export type patientsCreatePatientData = {
    body: PatientCreate;
    headers?: {
        /**
         * Idempotency-Key
         */
        'Idempotency-Key'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/patients';
};

export type patientsCreatePatientErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsCreatePatientError = patientsCreatePatientErrors[keyof patientsCreatePatientErrors];

export type patientsCreatePatientResponses = {
    /**
     * Successful Response
     */
    201: PatientDetailPublic;
};

export type patientsCreatePatientResponse = patientsCreatePatientResponses[keyof patientsCreatePatientResponses];

export type patientsReadPatientData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/patients/{patient_id}';
};

export type patientsReadPatientErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsReadPatientError = patientsReadPatientErrors[keyof patientsReadPatientErrors];

export type patientsReadPatientResponses = {
    /**
     * Successful Response
     */
    200: PatientDetailPublic;
};

export type patientsReadPatientResponse = patientsReadPatientResponses[keyof patientsReadPatientResponses];

export type patientsInvitePatientData = {
    body: PatientPortalInvitationCreate;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/patients/{patient_id}/portal-invitations';
};

export type patientsInvitePatientErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsInvitePatientError = patientsInvitePatientErrors[keyof patientsInvitePatientErrors];

export type patientsInvitePatientResponses = {
    /**
     * Successful Response
     */
    201: PatientPortalInvitationPublic;
};

export type patientsInvitePatientResponse = patientsInvitePatientResponses[keyof patientsInvitePatientResponses];

export type authPreviewPatientInvitationData = {
    body: PatientInvitationPreviewRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/patient-invitations/preview';
};

export type authPreviewPatientInvitationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authPreviewPatientInvitationError = authPreviewPatientInvitationErrors[keyof authPreviewPatientInvitationErrors];

export type authPreviewPatientInvitationResponses = {
    /**
     * Successful Response
     */
    200: PatientInvitationPreviewPublic;
};

export type authPreviewPatientInvitationResponse = authPreviewPatientInvitationResponses[keyof authPreviewPatientInvitationResponses];

export type authAcceptPatientInvitationData = {
    body: PatientInvitationAccept;
    path?: never;
    query?: never;
    url: '/api/v1/auth/patient-invitations/accept';
};

export type authAcceptPatientInvitationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authAcceptPatientInvitationError = authAcceptPatientInvitationErrors[keyof authAcceptPatientInvitationErrors];

export type authAcceptPatientInvitationResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type authAcceptPatientInvitationResponse = authAcceptPatientInvitationResponses[keyof authAcceptPatientInvitationResponses];

export type platformPlatformLoginData = {
    body: PlatformLogin;
    path?: never;
    query?: never;
    url: '/api/v1/platform/auth/login';
};

export type platformPlatformLoginErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type platformPlatformLoginError = platformPlatformLoginErrors[keyof platformPlatformLoginErrors];

export type platformPlatformLoginResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type platformPlatformLoginResponse = platformPlatformLoginResponses[keyof platformPlatformLoginResponses];

export type platformPlatformLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/platform/auth/logout';
};

export type platformPlatformLogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type platformPlatformLogoutResponse = platformPlatformLogoutResponses[keyof platformPlatformLogoutResponses];

export type platformPlatformMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/platform/auth/me';
};

export type platformPlatformMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type platformPlatformMeError = platformPlatformMeErrors[keyof platformPlatformMeErrors];

export type platformPlatformMeResponses = {
    /**
     * Successful Response
     */
    200: PlatformMePublic;
};

export type platformPlatformMeResponse = platformPlatformMeResponses[keyof platformPlatformMeResponses];

export type platformPlatformClinicsData = {
    body?: never;
    headers?: {
        /**
         * X-Request-Id
         */
        'X-Request-ID'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/platform/clinics';
};

export type platformPlatformClinicsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type platformPlatformClinicsError = platformPlatformClinicsErrors[keyof platformPlatformClinicsErrors];

export type platformPlatformClinicsResponses = {
    /**
     * Successful Response
     */
    200: PlatformClinicsPublic;
};

export type platformPlatformClinicsResponse = platformPlatformClinicsResponses[keyof platformPlatformClinicsResponses];

export type platformPlatformPatientsData = {
    body?: never;
    headers?: {
        /**
         * X-Request-Id
         */
        'X-Request-ID'?: string | null;
    };
    path: {
        /**
         * Clinic Code
         */
        clinic_code: string;
    };
    query?: never;
    url: '/api/v1/platform/clinics/{clinic_code}/patients';
};

export type platformPlatformPatientsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type platformPlatformPatientsError = platformPlatformPatientsErrors[keyof platformPlatformPatientsErrors];

export type platformPlatformPatientsResponses = {
    /**
     * Response Platform-Platform Patients
     *
     * Successful Response
     */
    200: Array<PatientDetailPublic>;
};

export type platformPlatformPatientsResponse = platformPlatformPatientsResponses[keyof platformPlatformPatientsResponses];

export type platformPlatformPatientTimelineData = {
    body?: never;
    headers?: {
        /**
         * X-Request-Id
         */
        'X-Request-ID'?: string | null;
    };
    path: {
        /**
         * Clinic Code
         */
        clinic_code: string;
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/platform/clinics/{clinic_code}/patients/{patient_id}/timeline';
};

export type platformPlatformPatientTimelineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type platformPlatformPatientTimelineError = platformPlatformPatientTimelineErrors[keyof platformPlatformPatientTimelineErrors];

export type platformPlatformPatientTimelineResponses = {
    /**
     * Successful Response
     */
    200: PatientTimeline;
};

export type platformPlatformPatientTimelineResponse = platformPlatformPatientTimelineResponses[keyof platformPlatformPatientTimelineResponses];

export type platformPlatformAuditLogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/platform/audit';
};

export type platformPlatformAuditLogErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type platformPlatformAuditLogError = platformPlatformAuditLogErrors[keyof platformPlatformAuditLogErrors];

export type platformPlatformAuditLogResponses = {
    /**
     * Successful Response
     */
    200: PlatformAuditsPublic;
};

export type platformPlatformAuditLogResponse = platformPlatformAuditLogResponses[keyof platformPlatformAuditLogResponses];

export type patientsPatientTimelineData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/patients/{patient_id}/timeline';
};

export type patientsPatientTimelineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsPatientTimelineError = patientsPatientTimelineErrors[keyof patientsPatientTimelineErrors];

export type patientsPatientTimelineResponses = {
    /**
     * Successful Response
     */
    200: PatientTimeline;
};

export type patientsPatientTimelineResponse = patientsPatientTimelineResponses[keyof patientsPatientTimelineResponses];

export type patientsPatientGlanceData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/patients/{patient_id}/glance';
};

export type patientsPatientGlanceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsPatientGlanceError = patientsPatientGlanceErrors[keyof patientsPatientGlanceErrors];

export type patientsPatientGlanceResponses = {
    /**
     * Response Patients-Patient Glance
     *
     * Successful Response
     */
    200: GlancePublic | ClinicalGlancePublic;
};

export type patientsPatientGlanceResponse = patientsPatientGlanceResponses[keyof patientsPatientGlanceResponses];

export type teamTeamMembersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/team/members';
};

export type teamTeamMembersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type teamTeamMembersError = teamTeamMembersErrors[keyof teamTeamMembersErrors];

export type teamTeamMembersResponses = {
    /**
     * Successful Response
     */
    200: TeamMembersPublic;
};

export type teamTeamMembersResponse = teamTeamMembersResponses[keyof teamTeamMembersResponses];

export type entriesCreateData = {
    body: EntryCreate;
    path?: never;
    query?: never;
    url: '/api/v1/entries';
};

export type entriesCreateErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type entriesCreateError = entriesCreateErrors[keyof entriesCreateErrors];

export type entriesCreateResponses = {
    /**
     * Response Entries-Create
     *
     * Successful Response
     */
    201: EntryPublic | PatientTimelineEntry;
};

export type entriesCreateResponse = entriesCreateResponses[keyof entriesCreateResponses];

export type entriesReadData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/entries/{entry_id}';
};

export type entriesReadErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type entriesReadError = entriesReadErrors[keyof entriesReadErrors];

export type entriesReadResponses = {
    /**
     * Response Entries-Read
     *
     * Successful Response
     */
    200: EntryPublic | PatientTimelineEntry;
};

export type entriesReadResponse = entriesReadResponses[keyof entriesReadResponses];

export type entriesPatchData = {
    body: EntryPatch;
    headers?: {
        /**
         * If-Match
         */
        'If-Match'?: string | null;
    };
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/entries/{entry_id}';
};

export type entriesPatchErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type entriesPatchError = entriesPatchErrors[keyof entriesPatchErrors];

export type entriesPatchResponses = {
    /**
     * Response Entries-Patch
     *
     * Successful Response
     */
    200: EntryPublic | PatientTimelineEntry;
};

export type entriesPatchResponse = entriesPatchResponses[keyof entriesPatchResponses];

export type entriesVersionsData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/entries/{entry_id}/versions';
};

export type entriesVersionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type entriesVersionsError = entriesVersionsErrors[keyof entriesVersionsErrors];

export type entriesVersionsResponses = {
    /**
     * Successful Response
     */
    200: EntryVersionsPublic;
};

export type entriesVersionsResponse = entriesVersionsResponses[keyof entriesVersionsResponses];

export type entriesDiffData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
        /**
         * Version Id
         */
        version_id: string;
    };
    query: {
        /**
         * Against
         */
        against: string;
    };
    url: '/api/v1/entries/{entry_id}/versions/{version_id}/diff';
};

export type entriesDiffErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type entriesDiffError = entriesDiffErrors[keyof entriesDiffErrors];

export type entriesDiffResponses = {
    /**
     * Successful Response
     */
    200: DiffPublic;
};

export type entriesDiffResponse = entriesDiffResponses[keyof entriesDiffResponses];

export type entriesRevertData = {
    body?: never;
    headers?: {
        /**
         * If-Match
         */
        'If-Match'?: string | null;
    };
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
        /**
         * Version Id
         */
        version_id: string;
    };
    query?: never;
    url: '/api/v1/entries/{entry_id}/versions/{version_id}/revert';
};

export type entriesRevertErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type entriesRevertError = entriesRevertErrors[keyof entriesRevertErrors];

export type entriesRevertResponses = {
    /**
     * Response Entries-Revert
     *
     * Successful Response
     */
    200: EntryPublic | PatientTimelineEntry;
};

export type entriesRevertResponse = entriesRevertResponses[keyof entriesRevertResponses];

export type collaborationListCommentsData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/entries/{entry_id}/comments';
};

export type collaborationListCommentsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collaborationListCommentsError = collaborationListCommentsErrors[keyof collaborationListCommentsErrors];

export type collaborationListCommentsResponses = {
    /**
     * Response Collaboration-List Comments
     *
     * Successful Response
     */
    200: Array<CommentPublic>;
};

export type collaborationListCommentsResponse = collaborationListCommentsResponses[keyof collaborationListCommentsResponses];

export type collaborationCreateCommentData = {
    body: CommentCreate;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/entries/{entry_id}/comments';
};

export type collaborationCreateCommentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collaborationCreateCommentError = collaborationCreateCommentErrors[keyof collaborationCreateCommentErrors];

export type collaborationCreateCommentResponses = {
    /**
     * Successful Response
     */
    201: CommentPublic;
};

export type collaborationCreateCommentResponse = collaborationCreateCommentResponses[keyof collaborationCreateCommentResponses];

export type collaborationReplyData = {
    body: CommentCreate;
    path: {
        /**
         * Comment Id
         */
        comment_id: string;
    };
    query?: never;
    url: '/api/v1/comments/{comment_id}/replies';
};

export type collaborationReplyErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collaborationReplyError = collaborationReplyErrors[keyof collaborationReplyErrors];

export type collaborationReplyResponses = {
    /**
     * Successful Response
     */
    201: CommentPublic;
};

export type collaborationReplyResponse = collaborationReplyResponses[keyof collaborationReplyResponses];

export type collaborationResolveData = {
    body?: never;
    path: {
        /**
         * Comment Id
         */
        comment_id: string;
    };
    query?: never;
    url: '/api/v1/comments/{comment_id}/resolve';
};

export type collaborationResolveErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collaborationResolveError = collaborationResolveErrors[keyof collaborationResolveErrors];

export type collaborationResolveResponses = {
    /**
     * Successful Response
     */
    200: CommentPublic;
};

export type collaborationResolveResponse = collaborationResolveResponses[keyof collaborationResolveResponses];

export type collaborationAssignData = {
    body: AssignmentUpdate;
    path: {
        /**
         * Comment Id
         */
        comment_id: string;
    };
    query?: never;
    url: '/api/v1/comments/{comment_id}/assignment';
};

export type collaborationAssignErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collaborationAssignError = collaborationAssignErrors[keyof collaborationAssignErrors];

export type collaborationAssignResponses = {
    /**
     * Successful Response
     */
    200: CommentPublic;
};

export type collaborationAssignResponse = collaborationAssignResponses[keyof collaborationAssignResponses];

export type trustCreateHighlightData = {
    body: HighlightCreate;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/entries/{entry_id}/highlights';
};

export type trustCreateHighlightErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustCreateHighlightError = trustCreateHighlightErrors[keyof trustCreateHighlightErrors];

export type trustCreateHighlightResponses = {
    /**
     * Successful Response
     */
    201: HighlightPublic;
};

export type trustCreateHighlightResponse = trustCreateHighlightResponses[keyof trustCreateHighlightResponses];

export type trustAcceptData = {
    body?: never;
    headers?: {
        /**
         * Idempotency-Key
         */
        'Idempotency-Key'?: string | null;
    };
    path: {
        /**
         * Highlight Id
         */
        highlight_id: string;
    };
    query?: never;
    url: '/api/v1/highlights/{highlight_id}/accept';
};

export type trustAcceptErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustAcceptError = trustAcceptErrors[keyof trustAcceptErrors];

export type trustAcceptResponses = {
    /**
     * Successful Response
     */
    200: HighlightPublic;
};

export type trustAcceptResponse = trustAcceptResponses[keyof trustAcceptResponses];

export type trustRejectData = {
    body?: never;
    headers?: {
        /**
         * Idempotency-Key
         */
        'Idempotency-Key'?: string | null;
    };
    path: {
        /**
         * Highlight Id
         */
        highlight_id: string;
    };
    query?: never;
    url: '/api/v1/highlights/{highlight_id}/reject';
};

export type trustRejectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustRejectError = trustRejectErrors[keyof trustRejectErrors];

export type trustRejectResponses = {
    /**
     * Successful Response
     */
    200: HighlightPublic;
};

export type trustRejectResponse = trustRejectResponses[keyof trustRejectResponses];

export type trustPinData = {
    body?: never;
    headers?: {
        /**
         * Idempotency-Key
         */
        'Idempotency-Key'?: string | null;
    };
    path: {
        /**
         * Highlight Id
         */
        highlight_id: string;
    };
    query?: never;
    url: '/api/v1/highlights/{highlight_id}/pin';
};

export type trustPinErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustPinError = trustPinErrors[keyof trustPinErrors];

export type trustPinResponses = {
    /**
     * Successful Response
     */
    200: HighlightPublic;
};

export type trustPinResponse = trustPinResponses[keyof trustPinResponses];

export type trustFeedbackData = {
    body: ImportanceFeedbackCreate;
    headers: {
        /**
         * Idempotency-Key
         */
        'Idempotency-Key': string;
    };
    path: {
        /**
         * Highlight Id
         */
        highlight_id: string;
    };
    query?: never;
    url: '/api/v1/highlights/{highlight_id}/feedback';
};

export type trustFeedbackErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustFeedbackError = trustFeedbackErrors[keyof trustFeedbackErrors];

export type trustFeedbackResponses = {
    /**
     * Successful Response
     */
    200: HighlightPublic;
};

export type trustFeedbackResponse = trustFeedbackResponses[keyof trustFeedbackResponses];

export type trustDecisionExplanationData = {
    body?: never;
    path: {
        /**
         * Highlight Id
         */
        highlight_id: string;
    };
    query?: never;
    url: '/api/v1/highlights/{highlight_id}/decision-explanation';
};

export type trustDecisionExplanationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustDecisionExplanationError = trustDecisionExplanationErrors[keyof trustDecisionExplanationErrors];

export type trustDecisionExplanationResponses = {
    /**
     * Successful Response
     */
    200: DecisionExplanationPublic;
};

export type trustDecisionExplanationResponse = trustDecisionExplanationResponses[keyof trustDecisionExplanationResponses];

export type trustRequestReviewData = {
    body: ReviewRequestCreate;
    path: {
        /**
         * Highlight Id
         */
        highlight_id: string;
    };
    query?: never;
    url: '/api/v1/highlights/{highlight_id}/request-review';
};

export type trustRequestReviewErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustRequestReviewError = trustRequestReviewErrors[keyof trustRequestReviewErrors];

export type trustRequestReviewResponses = {
    /**
     * Successful Response
     */
    200: HighlightPublic;
};

export type trustRequestReviewResponse = trustRequestReviewResponses[keyof trustRequestReviewResponses];

export type trustRecordImportanceImpressionData = {
    body: ImportanceImpressionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/importance-impressions';
};

export type trustRecordImportanceImpressionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustRecordImportanceImpressionError = trustRecordImportanceImpressionErrors[keyof trustRecordImportanceImpressionErrors];

export type trustRecordImportanceImpressionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type trustRecordImportanceImpressionResponse = trustRecordImportanceImpressionResponses[keyof trustRecordImportanceImpressionResponses];

export type trustProvenanceResolveData = {
    body?: never;
    path: {
        /**
         * Pointer Id
         */
        pointer_id: string;
    };
    query?: never;
    url: '/api/v1/provenance/{pointer_id}/resolve';
};

export type trustProvenanceResolveErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustProvenanceResolveError = trustProvenanceResolveErrors[keyof trustProvenanceResolveErrors];

export type trustProvenanceResolveResponses = {
    /**
     * Successful Response
     */
    200: ProvenanceResolved;
};

export type trustProvenanceResolveResponse = trustProvenanceResolveResponses[keyof trustProvenanceResolveResponses];

export type trustClinicalFactsForPatientData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/patients/{patient_id}/clinical-facts';
};

export type trustClinicalFactsForPatientErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustClinicalFactsForPatientError = trustClinicalFactsForPatientErrors[keyof trustClinicalFactsForPatientErrors];

export type trustClinicalFactsForPatientResponses = {
    /**
     * Response Trust-Clinical Facts For Patient
     *
     * Successful Response
     */
    200: Array<ClinicalFactAssertionPublic>;
};

export type trustClinicalFactsForPatientResponse = trustClinicalFactsForPatientResponses[keyof trustClinicalFactsForPatientResponses];

export type trustConflictsForPatientData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/patients/{patient_id}/conflicts';
};

export type trustConflictsForPatientErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustConflictsForPatientError = trustConflictsForPatientErrors[keyof trustConflictsForPatientErrors];

export type trustConflictsForPatientResponses = {
    /**
     * Response Trust-Conflicts For Patient
     *
     * Successful Response
     */
    200: Array<ConflictPublic>;
};

export type trustConflictsForPatientResponse = trustConflictsForPatientResponses[keyof trustConflictsForPatientResponses];

export type trustResolveConflictData = {
    body: ConflictResolve;
    path: {
        /**
         * Conflict Id
         */
        conflict_id: string;
    };
    query?: never;
    url: '/api/v1/conflicts/{conflict_id}/resolve';
};

export type trustResolveConflictErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustResolveConflictError = trustResolveConflictErrors[keyof trustResolveConflictErrors];

export type trustResolveConflictResponses = {
    /**
     * Successful Response
     */
    200: ConflictPublic;
};

export type trustResolveConflictResponse = trustResolveConflictResponses[keyof trustResolveConflictResponses];

export type trustCreatePatientSharingRequestData = {
    body: PatientSharingRequestCreate;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/entries/{entry_id}/patient-sharing-requests';
};

export type trustCreatePatientSharingRequestErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustCreatePatientSharingRequestError = trustCreatePatientSharingRequestErrors[keyof trustCreatePatientSharingRequestErrors];

export type trustCreatePatientSharingRequestResponses = {
    /**
     * Successful Response
     */
    201: PatientSharingRequestPublic;
};

export type trustCreatePatientSharingRequestResponse = trustCreatePatientSharingRequestResponses[keyof trustCreatePatientSharingRequestResponses];

export type trustListPatientSharingRequestsData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/patients/{patient_id}/patient-sharing-requests';
};

export type trustListPatientSharingRequestsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustListPatientSharingRequestsError = trustListPatientSharingRequestsErrors[keyof trustListPatientSharingRequestsErrors];

export type trustListPatientSharingRequestsResponses = {
    /**
     * Response Trust-List Patient Sharing Requests
     *
     * Successful Response
     */
    200: Array<PatientSharingRequestPublic>;
};

export type trustListPatientSharingRequestsResponse = trustListPatientSharingRequestsResponses[keyof trustListPatientSharingRequestsResponses];

export type trustPublishForPatientData = {
    body: PatientPublicationCreate;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/entries/{entry_id}/patient-publications';
};

export type trustPublishForPatientErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustPublishForPatientError = trustPublishForPatientErrors[keyof trustPublishForPatientErrors];

export type trustPublishForPatientResponses = {
    /**
     * Successful Response
     */
    201: PatientPublicationPublic;
};

export type trustPublishForPatientResponse = trustPublishForPatientResponses[keyof trustPublishForPatientResponses];

export type trustWithdrawPatientPublicationData = {
    body?: never;
    path: {
        /**
         * Publication Id
         */
        publication_id: string;
    };
    query?: never;
    url: '/api/v1/patient-publications/{publication_id}/withdraw';
};

export type trustWithdrawPatientPublicationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trustWithdrawPatientPublicationError = trustWithdrawPatientPublicationErrors[keyof trustWithdrawPatientPublicationErrors];

export type trustWithdrawPatientPublicationResponses = {
    /**
     * Successful Response
     */
    200: PatientPublicationPublic;
};

export type trustWithdrawPatientPublicationResponse = trustWithdrawPatientPublicationResponses[keyof trustWithdrawPatientPublicationResponses];

export type eventsEventStreamData = {
    body?: never;
    headers?: {
        /**
         * Last-Event-Id
         */
        'Last-Event-ID'?: number | null;
    };
    path?: never;
    query?: {
        /**
         * Snapshot
         */
        snapshot?: boolean;
    };
    url: '/api/v1/events/stream';
};

export type eventsEventStreamErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsEventStreamError = eventsEventStreamErrors[keyof eventsEventStreamErrors];

export type eventsEventStreamResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type decayPreviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/decay/preview';
};

export type decayPreviewErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type decayPreviewError = decayPreviewErrors[keyof decayPreviewErrors];

export type decayPreviewResponses = {
    /**
     * Successful Response
     */
    200: DecayPreviewPublic;
};

export type decayPreviewResponse = decayPreviewResponses[keyof decayPreviewResponses];

export type decayArchiveData = {
    body: DecayArchiveRequest;
    path?: never;
    query?: never;
    url: '/api/v1/decay/archive';
};

export type decayArchiveErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type decayArchiveError = decayArchiveErrors[keyof decayArchiveErrors];

export type decayArchiveResponses = {
    /**
     * Successful Response
     */
    200: DecayArchivePublic;
};

export type decayArchiveResponse = decayArchiveResponses[keyof decayArchiveResponses];

export type decayRehydrateData = {
    body?: never;
    path: {
        /**
         * Version Id
         */
        version_id: string;
    };
    query?: never;
    url: '/api/v1/decay/entries/{version_id}/rehydrate';
};

export type decayRehydrateErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type decayRehydrateError = decayRehydrateErrors[keyof decayRehydrateErrors];

export type decayRehydrateResponses = {
    /**
     * Successful Response
     */
    200: RehydratePublic;
};

export type decayRehydrateResponse = decayRehydrateResponses[keyof decayRehydrateResponses];

export type voiceCreateSessionData = {
    body: VoiceSessionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/voice/sessions';
};

export type voiceCreateSessionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type voiceCreateSessionError = voiceCreateSessionErrors[keyof voiceCreateSessionErrors];

export type voiceCreateSessionResponses = {
    /**
     * Successful Response
     */
    201: VoiceSessionPublic;
};

export type voiceCreateSessionResponse = voiceCreateSessionResponses[keyof voiceCreateSessionResponses];

export type voiceSessionStatusData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/voice/sessions/{session_id}';
};

export type voiceSessionStatusErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type voiceSessionStatusError = voiceSessionStatusErrors[keyof voiceSessionStatusErrors];

export type voiceSessionStatusResponses = {
    /**
     * Successful Response
     */
    200: VoiceSessionPublic;
};

export type voiceSessionStatusResponse = voiceSessionStatusResponses[keyof voiceSessionStatusResponses];

export type voiceJoinDeviceData = {
    body: VoiceDeviceJoin;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/voice/sessions/{session_id}/devices';
};

export type voiceJoinDeviceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type voiceJoinDeviceError = voiceJoinDeviceErrors[keyof voiceJoinDeviceErrors];

export type voiceJoinDeviceResponses = {
    /**
     * Successful Response
     */
    201: VoiceDevicePublic;
};

export type voiceJoinDeviceResponse = voiceJoinDeviceResponses[keyof voiceJoinDeviceResponses];

export type voiceAbandonDeviceData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/v1/voice/sessions/{session_id}/devices/{device_id}';
};

export type voiceAbandonDeviceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type voiceAbandonDeviceError = voiceAbandonDeviceErrors[keyof voiceAbandonDeviceErrors];

export type voiceAbandonDeviceResponses = {
    /**
     * Successful Response
     */
    200: VoiceDeviceAbandonPublic;
};

export type voiceAbandonDeviceResponse = voiceAbandonDeviceResponses[keyof voiceAbandonDeviceResponses];

export type voicePutChunkData = {
    body: Blob | File;
    headers: {
        /**
         * X-Chunk-Sha256
         */
        'X-Chunk-SHA256': string;
        /**
         * X-Chunk-Start-Ms
         */
        'X-Chunk-Start-Ms'?: number | null;
        /**
         * X-Chunk-End-Ms
         */
        'X-Chunk-End-Ms'?: number | null;
    };
    path: {
        /**
         * Session Id
         */
        session_id: string;
        /**
         * Device Id
         */
        device_id: string;
        /**
         * Chunk Index
         */
        chunk_index: number;
    };
    query?: never;
    url: '/api/v1/voice/sessions/{session_id}/devices/{device_id}/chunks/{chunk_index}';
};

export type voicePutChunkErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type voicePutChunkError = voicePutChunkErrors[keyof voicePutChunkErrors];

export type voicePutChunkResponses = {
    /**
     * Successful Response
     */
    200: AudioChunkAck;
};

export type voicePutChunkResponse = voicePutChunkResponses[keyof voicePutChunkResponses];

export type voiceSealDeviceData = {
    body: VoiceDeviceSeal;
    path: {
        /**
         * Session Id
         */
        session_id: string;
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/v1/voice/sessions/{session_id}/devices/{device_id}/seal';
};

export type voiceSealDeviceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type voiceSealDeviceError = voiceSealDeviceErrors[keyof voiceSealDeviceErrors];

export type voiceSealDeviceResponses = {
    /**
     * Successful Response
     */
    200: VoiceDeviceSealPublic;
};

export type voiceSealDeviceResponse = voiceSealDeviceResponses[keyof voiceSealDeviceResponses];

export type voiceGetChunkStatusData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/voice/sessions/{session_id}/chunks/status';
};

export type voiceGetChunkStatusErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type voiceGetChunkStatusError = voiceGetChunkStatusErrors[keyof voiceGetChunkStatusErrors];

export type voiceGetChunkStatusResponses = {
    /**
     * Successful Response
     */
    200: VoiceChunkStatus;
};

export type voiceGetChunkStatusResponse = voiceGetChunkStatusResponses[keyof voiceGetChunkStatusResponses];

export type voiceFinalizeData = {
    body: VoiceFinalizeRequest;
    headers: {
        /**
         * Idempotency-Key
         */
        'Idempotency-Key': string;
    };
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/voice/sessions/{session_id}/finalize';
};

export type voiceFinalizeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type voiceFinalizeError = voiceFinalizeErrors[keyof voiceFinalizeErrors];

export type voiceFinalizeResponses = {
    /**
     * Successful Response
     */
    202: VoiceFinalizePublic;
};

export type voiceFinalizeResponse = voiceFinalizeResponses[keyof voiceFinalizeResponses];

export type voiceTranscriptData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/voice/sessions/{session_id}/transcript';
};

export type voiceTranscriptErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type voiceTranscriptError = voiceTranscriptErrors[keyof voiceTranscriptErrors];

export type voiceTranscriptResponses = {
    /**
     * Successful Response
     */
    200: TranscriptRevisionPublic;
};

export type voiceTranscriptResponse = voiceTranscriptResponses[keyof voiceTranscriptResponses];

export type voiceCorrectData = {
    body: TranscriptCorrection;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/voice/sessions/{session_id}/transcript/correct';
};

export type voiceCorrectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type voiceCorrectError = voiceCorrectErrors[keyof voiceCorrectErrors];

export type voiceCorrectResponses = {
    /**
     * Successful Response
     */
    201: TranscriptRevisionPublic;
};

export type voiceCorrectResponse = voiceCorrectResponses[keyof voiceCorrectResponses];

export type voiceReanalyzeData = {
    body: VoiceReanalyzeRequest;
    headers: {
        /**
         * Idempotency-Key
         */
        'Idempotency-Key': string;
    };
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/voice/sessions/{session_id}/reanalyze';
};

export type voiceReanalyzeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type voiceReanalyzeError = voiceReanalyzeErrors[keyof voiceReanalyzeErrors];

export type voiceReanalyzeResponses = {
    /**
     * Successful Response
     */
    202: VoiceReanalyzePublic;
};

export type voiceReanalyzeResponse = voiceReanalyzeResponses[keyof voiceReanalyzeResponses];

export type voicePublishData = {
    body: VoicePublishRequest;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/voice/sessions/{session_id}/publish';
};

export type voicePublishErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type voicePublishError = voicePublishErrors[keyof voicePublishErrors];

export type voicePublishResponses = {
    /**
     * Successful Response
     */
    200: VoicePublishPublic;
};

export type voicePublishResponse = voicePublishResponses[keyof voicePublishResponses];

export type voiceAudioData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/voice/sessions/{session_id}/audio';
};

export type voiceAudioErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type voiceAudioError = voiceAudioErrors[keyof voiceAudioErrors];

export type voiceAudioResponses = {
    /**
     * Authorized normalized 16 kHz mono PCM audio
     */
    200: Blob | File;
};

export type voiceAudioResponse = voiceAudioResponses[keyof voiceAudioResponses];

export type voiceLiveStatusData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/voice/sessions/{session_id}/live';
};

export type voiceLiveStatusErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type voiceLiveStatusError = voiceLiveStatusErrors[keyof voiceLiveStatusErrors];

export type voiceLiveStatusResponses = {
    /**
     * Successful Response
     */
    200: LiveTranscriptAvailability;
};

export type voiceLiveStatusResponse = voiceLiveStatusResponses[keyof voiceLiveStatusResponses];
