/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyCareRouteImport } from './routes/my-care'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as PatientAcceptInvitationRouteImport } from './routes/patient/accept-invitation'
import { Route as PatientLoginRouteImport } from './routes/patient/login'
import { Route as PatientMyCareRouteImport } from './routes/patient/my-care'
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as PlatformLoginRouteImport } from './routes/platform/login'
import { Route as LayoutPatientsIndexRouteImport } from './routes/_layout/patients.index'
import { Route as LayoutPatientsPatientIdRouteImport } from './routes/_layout/patients.$patientId'
import { Route as LayoutPatientsNewRouteImport } from './routes/_layout/patients.new'
import { Route as MyCareVoiceSessionIdRouteImport } from './routes/my-care_.voice.$sessionId'
import { Route as MyCareVoiceCaptureRouteImport } from './routes/my-care_.voice.capture'
import { Route as PatientMyCareIndexRouteImport } from './routes/patient/my-care/index'
import { Route as PlatformClinicsClinicCodeRouteImport } from './routes/platform/clinics.$clinicCode'
import { Route as LayoutVoiceSessionIdReviewRouteImport } from './routes/_layout/voice.$sessionId.review'
import { Route as PatientMyCareVoiceSessionIdRouteImport } from './routes/patient/my-care/voice/$sessionId'
import { Route as PatientMyCareVoiceCaptureRouteImport } from './routes/patient/my-care/voice/capture'
import { Route as LayoutPatientsPatientIdVoiceCaptureRouteImport } from './routes/_layout/patients_.$patientId.voice.capture'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCareRoute = MyCareRouteImport.update({
  id: '/my-care',
  path: '/my-care',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const PatientAcceptInvitationRoute = PatientAcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => PatientRoute,
} as any)
const PatientLoginRoute = PatientLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMyCareRoute = PatientMyCareRouteImport.update({
  id: '/my-care',
  path: '/my-care',
  getParentRoute: () => PatientRoute,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformLoginRoute = PlatformLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PlatformRoute,
} as any)
const LayoutPatientsIndexRoute = LayoutPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPatientsPatientIdRoute = LayoutPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPatientsNewRoute = LayoutPatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => LayoutRoute,
} as any)
const MyCareVoiceSessionIdRoute = MyCareVoiceSessionIdRouteImport.update({
  id: '/my-care_/voice/$sessionId',
  path: '/my-care/voice/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCareVoiceCaptureRoute = MyCareVoiceCaptureRouteImport.update({
  id: '/my-care_/voice/capture',
  path: '/my-care/voice/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientMyCareIndexRoute = PatientMyCareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientMyCareRoute,
} as any)
const PlatformClinicsClinicCodeRoute =
  PlatformClinicsClinicCodeRouteImport.update({
    id: '/clinics/$clinicCode',
    path: '/clinics/$clinicCode',
    getParentRoute: () => PlatformRoute,
  } as any)
const LayoutVoiceSessionIdReviewRoute =
  LayoutVoiceSessionIdReviewRouteImport.update({
    id: '/voice/$sessionId/review',
    path: '/voice/$sessionId/review',
    getParentRoute: () => LayoutRoute,
  } as any)
const PatientMyCareVoiceSessionIdRoute =
  PatientMyCareVoiceSessionIdRouteImport.update({
    id: '/voice/$sessionId',
    path: '/voice/$sessionId',
    getParentRoute: () => PatientMyCareRoute,
  } as any)
const PatientMyCareVoiceCaptureRoute =
  PatientMyCareVoiceCaptureRouteImport.update({
    id: '/voice/capture',
    path: '/voice/capture',
    getParentRoute: () => PatientMyCareRoute,
  } as any)
const LayoutPatientsPatientIdVoiceCaptureRoute =
  LayoutPatientsPatientIdVoiceCaptureRouteImport.update({
    id: '/patients_/$patientId/voice/capture',
    path: '/patients/$patientId/voice/capture',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/my-care': typeof MyCareRoute
  '/patient': typeof PatientRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/admin': typeof LayoutAdminRoute
  '/patient/accept-invitation': typeof PatientAcceptInvitationRoute
  '/patient/login': typeof PatientLoginRoute
  '/patient/my-care': typeof PatientMyCareRouteWithChildren
  '/platform/login': typeof PlatformLoginRoute
  '/platform/': typeof PlatformIndexRoute
  '/patients/$patientId': typeof LayoutPatientsPatientIdRoute
  '/patients/new': typeof LayoutPatientsNewRoute
  '/my-care/voice/$sessionId': typeof MyCareVoiceSessionIdRoute
  '/my-care/voice/capture': typeof MyCareVoiceCaptureRoute
  '/platform/clinics/$clinicCode': typeof PlatformClinicsClinicCodeRoute
  '/patients/': typeof LayoutPatientsIndexRoute
  '/patient/my-care/': typeof PatientMyCareIndexRoute
  '/voice/$sessionId/review': typeof LayoutVoiceSessionIdReviewRoute
  '/patient/my-care/voice/$sessionId': typeof PatientMyCareVoiceSessionIdRoute
  '/patient/my-care/voice/capture': typeof PatientMyCareVoiceCaptureRoute
  '/patients/$patientId/voice/capture': typeof LayoutPatientsPatientIdVoiceCaptureRoute
}
export interface FileRoutesByTo {
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/my-care': typeof MyCareRoute
  '/patient': typeof PatientRouteWithChildren
  '/admin': typeof LayoutAdminRoute
  '/patient/accept-invitation': typeof PatientAcceptInvitationRoute
  '/patient/login': typeof PatientLoginRoute
  '/platform/login': typeof PlatformLoginRoute
  '/': typeof LayoutIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/patients/$patientId': typeof LayoutPatientsPatientIdRoute
  '/patients/new': typeof LayoutPatientsNewRoute
  '/my-care/voice/$sessionId': typeof MyCareVoiceSessionIdRoute
  '/my-care/voice/capture': typeof MyCareVoiceCaptureRoute
  '/platform/clinics/$clinicCode': typeof PlatformClinicsClinicCodeRoute
  '/patients': typeof LayoutPatientsIndexRoute
  '/patient/my-care': typeof PatientMyCareIndexRoute
  '/voice/$sessionId/review': typeof LayoutVoiceSessionIdReviewRoute
  '/patient/my-care/voice/$sessionId': typeof PatientMyCareVoiceSessionIdRoute
  '/patient/my-care/voice/capture': typeof PatientMyCareVoiceCaptureRoute
  '/patients/$patientId/voice/capture': typeof LayoutPatientsPatientIdVoiceCaptureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/my-care': typeof MyCareRoute
  '/patient': typeof PatientRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/_layout/admin': typeof LayoutAdminRoute
  '/patient/accept-invitation': typeof PatientAcceptInvitationRoute
  '/patient/login': typeof PatientLoginRoute
  '/patient/my-care': typeof PatientMyCareRouteWithChildren
  '/platform/login': typeof PlatformLoginRoute
  '/_layout/': typeof LayoutIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/_layout/patients/$patientId': typeof LayoutPatientsPatientIdRoute
  '/_layout/patients/new': typeof LayoutPatientsNewRoute
  '/my-care_/voice/$sessionId': typeof MyCareVoiceSessionIdRoute
  '/my-care_/voice/capture': typeof MyCareVoiceCaptureRoute
  '/platform/clinics/$clinicCode': typeof PlatformClinicsClinicCodeRoute
  '/_layout/patients/': typeof LayoutPatientsIndexRoute
  '/patient/my-care/': typeof PatientMyCareIndexRoute
  '/_layout/voice/$sessionId/review': typeof LayoutVoiceSessionIdReviewRoute
  '/patient/my-care/voice/$sessionId': typeof PatientMyCareVoiceSessionIdRoute
  '/patient/my-care/voice/capture': typeof PatientMyCareVoiceCaptureRoute
  '/_layout/patients_/$patientId/voice/capture': typeof LayoutPatientsPatientIdVoiceCaptureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/login'
    | '/my-care'
    | '/patient'
    | '/platform'
    | '/admin'
    | '/patient/accept-invitation'
    | '/patient/login'
    | '/patient/my-care'
    | '/platform/login'
    | '/platform/'
    | '/patients/$patientId'
    | '/patients/new'
    | '/my-care/voice/$sessionId'
    | '/my-care/voice/capture'
    | '/platform/clinics/$clinicCode'
    | '/patients/'
    | '/patient/my-care/'
    | '/voice/$sessionId/review'
    | '/patient/my-care/voice/$sessionId'
    | '/patient/my-care/voice/capture'
    | '/patients/$patientId/voice/capture'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invitation'
    | '/login'
    | '/my-care'
    | '/patient'
    | '/admin'
    | '/patient/accept-invitation'
    | '/patient/login'
    | '/platform/login'
    | '/'
    | '/platform'
    | '/patients/$patientId'
    | '/patients/new'
    | '/my-care/voice/$sessionId'
    | '/my-care/voice/capture'
    | '/platform/clinics/$clinicCode'
    | '/patients'
    | '/patient/my-care'
    | '/voice/$sessionId/review'
    | '/patient/my-care/voice/$sessionId'
    | '/patient/my-care/voice/capture'
    | '/patients/$patientId/voice/capture'
  id:
    | '__root__'
    | '/_layout'
    | '/accept-invitation'
    | '/login'
    | '/my-care'
    | '/patient'
    | '/platform'
    | '/_layout/admin'
    | '/patient/accept-invitation'
    | '/patient/login'
    | '/patient/my-care'
    | '/platform/login'
    | '/_layout/'
    | '/platform/'
    | '/_layout/patients/$patientId'
    | '/_layout/patients/new'
    | '/my-care_/voice/$sessionId'
    | '/my-care_/voice/capture'
    | '/platform/clinics/$clinicCode'
    | '/_layout/patients/'
    | '/patient/my-care/'
    | '/_layout/voice/$sessionId/review'
    | '/patient/my-care/voice/$sessionId'
    | '/patient/my-care/voice/capture'
    | '/_layout/patients_/$patientId/voice/capture'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  LoginRoute: typeof LoginRoute
  MyCareRoute: typeof MyCareRoute
  PatientRoute: typeof PatientRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
  MyCareVoiceSessionIdRoute: typeof MyCareVoiceSessionIdRoute
  MyCareVoiceCaptureRoute: typeof MyCareVoiceCaptureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-care': {
      id: '/my-care'
      path: '/my-care'
      fullPath: '/my-care'
      preLoaderRoute: typeof MyCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/patient/accept-invitation': {
      id: '/patient/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/patient/accept-invitation'
      preLoaderRoute: typeof PatientAcceptInvitationRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/login': {
      id: '/patient/login'
      path: '/login'
      fullPath: '/patient/login'
      preLoaderRoute: typeof PatientLoginRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/my-care': {
      id: '/patient/my-care'
      path: '/my-care'
      fullPath: '/patient/my-care'
      preLoaderRoute: typeof PatientMyCareRouteImport
      parentRoute: typeof PatientRoute
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/login': {
      id: '/platform/login'
      path: '/login'
      fullPath: '/platform/login'
      preLoaderRoute: typeof PlatformLoginRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_layout/patients/': {
      id: '/_layout/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof LayoutPatientsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/patients/$patientId': {
      id: '/_layout/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof LayoutPatientsPatientIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/patients/new': {
      id: '/_layout/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof LayoutPatientsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/my-care_/voice/$sessionId': {
      id: '/my-care_/voice/$sessionId'
      path: '/my-care/voice/$sessionId'
      fullPath: '/my-care/voice/$sessionId'
      preLoaderRoute: typeof MyCareVoiceSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-care_/voice/capture': {
      id: '/my-care_/voice/capture'
      path: '/my-care/voice/capture'
      fullPath: '/my-care/voice/capture'
      preLoaderRoute: typeof MyCareVoiceCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/my-care/': {
      id: '/patient/my-care/'
      path: '/'
      fullPath: '/patient/my-care/'
      preLoaderRoute: typeof PatientMyCareIndexRouteImport
      parentRoute: typeof PatientMyCareRoute
    }
    '/platform/clinics/$clinicCode': {
      id: '/platform/clinics/$clinicCode'
      path: '/clinics/$clinicCode'
      fullPath: '/platform/clinics/$clinicCode'
      preLoaderRoute: typeof PlatformClinicsClinicCodeRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_layout/voice/$sessionId/review': {
      id: '/_layout/voice/$sessionId/review'
      path: '/voice/$sessionId/review'
      fullPath: '/voice/$sessionId/review'
      preLoaderRoute: typeof LayoutVoiceSessionIdReviewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/patient/my-care/voice/$sessionId': {
      id: '/patient/my-care/voice/$sessionId'
      path: '/voice/$sessionId'
      fullPath: '/patient/my-care/voice/$sessionId'
      preLoaderRoute: typeof PatientMyCareVoiceSessionIdRouteImport
      parentRoute: typeof PatientMyCareRoute
    }
    '/patient/my-care/voice/capture': {
      id: '/patient/my-care/voice/capture'
      path: '/voice/capture'
      fullPath: '/patient/my-care/voice/capture'
      preLoaderRoute: typeof PatientMyCareVoiceCaptureRouteImport
      parentRoute: typeof PatientMyCareRoute
    }
    '/_layout/patients_/$patientId/voice/capture': {
      id: '/_layout/patients_/$patientId/voice/capture'
      path: '/patients/$patientId/voice/capture'
      fullPath: '/patients/$patientId/voice/capture'
      preLoaderRoute: typeof LayoutPatientsPatientIdVoiceCaptureRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutPatientsPatientIdRoute: typeof LayoutPatientsPatientIdRoute
  LayoutPatientsNewRoute: typeof LayoutPatientsNewRoute
  LayoutPatientsIndexRoute: typeof LayoutPatientsIndexRoute
  LayoutVoiceSessionIdReviewRoute: typeof LayoutVoiceSessionIdReviewRoute
  LayoutPatientsPatientIdVoiceCaptureRoute: typeof LayoutPatientsPatientIdVoiceCaptureRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutPatientsPatientIdRoute: LayoutPatientsPatientIdRoute,
  LayoutPatientsNewRoute: LayoutPatientsNewRoute,
  LayoutPatientsIndexRoute: LayoutPatientsIndexRoute,
  LayoutVoiceSessionIdReviewRoute: LayoutVoiceSessionIdReviewRoute,
  LayoutPatientsPatientIdVoiceCaptureRoute:
    LayoutPatientsPatientIdVoiceCaptureRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface PatientMyCareRouteChildren {
  PatientMyCareIndexRoute: typeof PatientMyCareIndexRoute
  PatientMyCareVoiceSessionIdRoute: typeof PatientMyCareVoiceSessionIdRoute
  PatientMyCareVoiceCaptureRoute: typeof PatientMyCareVoiceCaptureRoute
}

const PatientMyCareRouteChildren: PatientMyCareRouteChildren = {
  PatientMyCareIndexRoute: PatientMyCareIndexRoute,
  PatientMyCareVoiceSessionIdRoute: PatientMyCareVoiceSessionIdRoute,
  PatientMyCareVoiceCaptureRoute: PatientMyCareVoiceCaptureRoute,
}

const PatientMyCareRouteWithChildren = PatientMyCareRoute._addFileChildren(
  PatientMyCareRouteChildren,
)

interface PatientRouteChildren {
  PatientAcceptInvitationRoute: typeof PatientAcceptInvitationRoute
  PatientLoginRoute: typeof PatientLoginRoute
  PatientMyCareRoute: typeof PatientMyCareRouteWithChildren
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAcceptInvitationRoute: PatientAcceptInvitationRoute,
  PatientLoginRoute: PatientLoginRoute,
  PatientMyCareRoute: PatientMyCareRouteWithChildren,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

interface PlatformRouteChildren {
  PlatformLoginRoute: typeof PlatformLoginRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  PlatformClinicsClinicCodeRoute: typeof PlatformClinicsClinicCodeRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformLoginRoute: PlatformLoginRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  PlatformClinicsClinicCodeRoute: PlatformClinicsClinicCodeRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  LoginRoute: LoginRoute,
  MyCareRoute: MyCareRoute,
  PatientRoute: PatientRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
  MyCareVoiceSessionIdRoute: MyCareVoiceSessionIdRoute,
  MyCareVoiceCaptureRoute: MyCareVoiceCaptureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
