/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutMyCareRouteImport } from './routes/_layout/my-care'
import { Route as LayoutPatientsIndexRouteImport } from './routes/_layout/patients.index'
import { Route as LayoutPatientsPatientIdRouteImport } from './routes/_layout/patients.$patientId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMyCareRoute = LayoutMyCareRouteImport.update({
  id: '/my-care',
  path: '/my-care',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPatientsIndexRoute = LayoutPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPatientsPatientIdRoute = LayoutPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRoute
  '/my-care': typeof LayoutMyCareRoute
  '/patients/$patientId': typeof LayoutPatientsPatientIdRoute
  '/patients/': typeof LayoutPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRoute
  '/my-care': typeof LayoutMyCareRoute
  '/': typeof LayoutIndexRoute
  '/patients/$patientId': typeof LayoutPatientsPatientIdRoute
  '/patients': typeof LayoutPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/my-care': typeof LayoutMyCareRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/patients/$patientId': typeof LayoutPatientsPatientIdRoute
  '/_layout/patients/': typeof LayoutPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/my-care'
    | '/patients/$patientId'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/my-care'
    | '/'
    | '/patients/$patientId'
    | '/patients'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/admin'
    | '/_layout/my-care'
    | '/_layout/'
    | '/_layout/patients/$patientId'
    | '/_layout/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/my-care': {
      id: '/_layout/my-care'
      path: '/my-care'
      fullPath: '/my-care'
      preLoaderRoute: typeof LayoutMyCareRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/patients/': {
      id: '/_layout/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof LayoutPatientsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/patients/$patientId': {
      id: '/_layout/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof LayoutPatientsPatientIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutMyCareRoute: typeof LayoutMyCareRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutPatientsPatientIdRoute: typeof LayoutPatientsPatientIdRoute
  LayoutPatientsIndexRoute: typeof LayoutPatientsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutMyCareRoute: LayoutMyCareRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutPatientsPatientIdRoute: LayoutPatientsPatientIdRoute,
  LayoutPatientsIndexRoute: LayoutPatientsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
