/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutMyCareRouteImport } from './routes/_layout/my-care'
import { Route as LayoutPatientsIndexRouteImport } from './routes/_layout/patients.index'
import { Route as LayoutPatientsPatientIdRouteImport } from './routes/_layout/patients.$patientId'
import { Route as LayoutMyCareVoiceSessionIdRouteImport } from './routes/_layout/my-care_.voice.$sessionId'
import { Route as LayoutMyCareVoiceCaptureRouteImport } from './routes/_layout/my-care_.voice.capture'
import { Route as LayoutVoiceSessionIdReviewRouteImport } from './routes/_layout/voice.$sessionId.review'
import { Route as LayoutPatientsPatientIdVoiceCaptureRouteImport } from './routes/_layout/patients_.$patientId.voice.capture'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMyCareRoute = LayoutMyCareRouteImport.update({
  id: '/my-care',
  path: '/my-care',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPatientsIndexRoute = LayoutPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPatientsPatientIdRoute = LayoutPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMyCareVoiceSessionIdRoute =
  LayoutMyCareVoiceSessionIdRouteImport.update({
    id: '/my-care_/voice/$sessionId',
    path: '/my-care/voice/$sessionId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutMyCareVoiceCaptureRoute =
  LayoutMyCareVoiceCaptureRouteImport.update({
    id: '/my-care_/voice/capture',
    path: '/my-care/voice/capture',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutVoiceSessionIdReviewRoute =
  LayoutVoiceSessionIdReviewRouteImport.update({
    id: '/voice/$sessionId/review',
    path: '/voice/$sessionId/review',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPatientsPatientIdVoiceCaptureRoute =
  LayoutPatientsPatientIdVoiceCaptureRouteImport.update({
    id: '/patients_/$patientId/voice/capture',
    path: '/patients/$patientId/voice/capture',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRoute
  '/my-care': typeof LayoutMyCareRoute
  '/patients/$patientId': typeof LayoutPatientsPatientIdRoute
  '/patients/': typeof LayoutPatientsIndexRoute
  '/my-care/voice/$sessionId': typeof LayoutMyCareVoiceSessionIdRoute
  '/my-care/voice/capture': typeof LayoutMyCareVoiceCaptureRoute
  '/voice/$sessionId/review': typeof LayoutVoiceSessionIdReviewRoute
  '/patients/$patientId/voice/capture': typeof LayoutPatientsPatientIdVoiceCaptureRoute
}
export interface FileRoutesByTo {
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRoute
  '/my-care': typeof LayoutMyCareRoute
  '/': typeof LayoutIndexRoute
  '/patients/$patientId': typeof LayoutPatientsPatientIdRoute
  '/patients': typeof LayoutPatientsIndexRoute
  '/my-care/voice/$sessionId': typeof LayoutMyCareVoiceSessionIdRoute
  '/my-care/voice/capture': typeof LayoutMyCareVoiceCaptureRoute
  '/voice/$sessionId/review': typeof LayoutVoiceSessionIdReviewRoute
  '/patients/$patientId/voice/capture': typeof LayoutPatientsPatientIdVoiceCaptureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/my-care': typeof LayoutMyCareRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/patients/$patientId': typeof LayoutPatientsPatientIdRoute
  '/_layout/patients/': typeof LayoutPatientsIndexRoute
  '/_layout/my-care_/voice/$sessionId': typeof LayoutMyCareVoiceSessionIdRoute
  '/_layout/my-care_/voice/capture': typeof LayoutMyCareVoiceCaptureRoute
  '/_layout/voice/$sessionId/review': typeof LayoutVoiceSessionIdReviewRoute
  '/_layout/patients_/$patientId/voice/capture': typeof LayoutPatientsPatientIdVoiceCaptureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/login'
    | '/admin'
    | '/my-care'
    | '/patients/$patientId'
    | '/patients/'
    | '/my-care/voice/$sessionId'
    | '/my-care/voice/capture'
    | '/voice/$sessionId/review'
    | '/patients/$patientId/voice/capture'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invitation'
    | '/login'
    | '/admin'
    | '/my-care'
    | '/'
    | '/patients/$patientId'
    | '/patients'
    | '/my-care/voice/$sessionId'
    | '/my-care/voice/capture'
    | '/voice/$sessionId/review'
    | '/patients/$patientId/voice/capture'
  id:
    | '__root__'
    | '/_layout'
    | '/accept-invitation'
    | '/login'
    | '/_layout/admin'
    | '/_layout/my-care'
    | '/_layout/'
    | '/_layout/patients/$patientId'
    | '/_layout/patients/'
    | '/_layout/my-care_/voice/$sessionId'
    | '/_layout/my-care_/voice/capture'
    | '/_layout/voice/$sessionId/review'
    | '/_layout/patients_/$patientId/voice/capture'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/my-care': {
      id: '/_layout/my-care'
      path: '/my-care'
      fullPath: '/my-care'
      preLoaderRoute: typeof LayoutMyCareRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/patients/': {
      id: '/_layout/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof LayoutPatientsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/patients/$patientId': {
      id: '/_layout/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof LayoutPatientsPatientIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/my-care_/voice/$sessionId': {
      id: '/_layout/my-care_/voice/$sessionId'
      path: '/my-care/voice/$sessionId'
      fullPath: '/my-care/voice/$sessionId'
      preLoaderRoute: typeof LayoutMyCareVoiceSessionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/my-care_/voice/capture': {
      id: '/_layout/my-care_/voice/capture'
      path: '/my-care/voice/capture'
      fullPath: '/my-care/voice/capture'
      preLoaderRoute: typeof LayoutMyCareVoiceCaptureRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/voice/$sessionId/review': {
      id: '/_layout/voice/$sessionId/review'
      path: '/voice/$sessionId/review'
      fullPath: '/voice/$sessionId/review'
      preLoaderRoute: typeof LayoutVoiceSessionIdReviewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/patients_/$patientId/voice/capture': {
      id: '/_layout/patients_/$patientId/voice/capture'
      path: '/patients/$patientId/voice/capture'
      fullPath: '/patients/$patientId/voice/capture'
      preLoaderRoute: typeof LayoutPatientsPatientIdVoiceCaptureRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutMyCareRoute: typeof LayoutMyCareRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutPatientsPatientIdRoute: typeof LayoutPatientsPatientIdRoute
  LayoutPatientsIndexRoute: typeof LayoutPatientsIndexRoute
  LayoutMyCareVoiceSessionIdRoute: typeof LayoutMyCareVoiceSessionIdRoute
  LayoutMyCareVoiceCaptureRoute: typeof LayoutMyCareVoiceCaptureRoute
  LayoutVoiceSessionIdReviewRoute: typeof LayoutVoiceSessionIdReviewRoute
  LayoutPatientsPatientIdVoiceCaptureRoute: typeof LayoutPatientsPatientIdVoiceCaptureRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutMyCareRoute: LayoutMyCareRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutPatientsPatientIdRoute: LayoutPatientsPatientIdRoute,
  LayoutPatientsIndexRoute: LayoutPatientsIndexRoute,
  LayoutMyCareVoiceSessionIdRoute: LayoutMyCareVoiceSessionIdRoute,
  LayoutMyCareVoiceCaptureRoute: LayoutMyCareVoiceCaptureRoute,
  LayoutVoiceSessionIdReviewRoute: LayoutVoiceSessionIdReviewRoute,
  LayoutPatientsPatientIdVoiceCaptureRoute:
    LayoutPatientsPatientIdVoiceCaptureRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
